<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Image_foot1_gxp0_ifrm</name>
   <tag></tag>
   <elementGuidId>7236f9f0-3ba9-472c-9443-ac3ee76ab3fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gxp0_ifrm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gxp0_ifrm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0195d04e-6196-441a-8f6f-f4431ba3b11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gxp0_ifrm</value>
      <webElementGuid>6f084b7b-d262-402a-be6b-eaed04eca1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://172.29.35.250:8080/PortalSena16/servlet/com.portalsena.wppromptactividadeconomica?,,gxPopupLevel%3D0%3B</value>
      <webElementGuid>94298ba2-ea78-4906-812d-394cb59c7113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Com.portalsena</value>
      <webElementGuid>17e4f475-c1f8-4fe6-a8e8-bc3110b5486e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gxp0_ifrm&quot;)</value>
      <webElementGuid>11507c50-312f-4705-ac71-3efc1fa9600a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gxp0_ifrm']</value>
      <webElementGuid>154a289e-af62-40a4-a018-3803678935c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gxp0_c']/iframe</value>
      <webElementGuid>5d4af75b-09c5-4e82-91df-6870931d6490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>dc55c635-519b-4461-9b91-89928d3515a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'gxp0_ifrm' and @src = 'http://172.29.35.250:8080/PortalSena16/servlet/com.portalsena.wppromptactividadeconomica?,,gxPopupLevel%3D0%3B' and @title = 'Com.portalsena']</value>
      <webElementGuid>34305579-bcf3-4de5-8718-7b9ba8c56439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
