<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Seleccione_W0031W0007W0012SELACTIVIDAD</name>
   <tag></tag>
   <elementGuidId>10bf075f-e47d-4bb9-9ba1-ca086a42dfa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0031W0007W0012SELACTIVIDAD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='W0031W0007W0012SELACTIVIDAD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b613de70-0392-495d-8d5d-00ee0669fbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/PortalSena16/static/Resources/prompt.png</value>
      <webElementGuid>3a6c8910-d764-4a53-86fb-9cf29bc93b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>26fb448a-0b7d-4208-95b0-7339c4f22fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012SELACTIVIDAD</value>
      <webElementGuid>574b4a72-cc65-4ae4-973d-100bd0e87102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sel Actividad</value>
      <webElementGuid>e200a360-9313-49c8-944d-f40b1ff12f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Seleccionar Actividad Económica</value>
      <webElementGuid>dab92306-0e93-4733-a863-999e663ac73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 157,'W0031W0007W0012',false,'',0)</value>
      <webElementGuid>e984e8ee-1855-4160-863d-a5dbe4892c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt-control</name>
      <type>Main</type>
      <value>SELACTIVIDAD</value>
      <webElementGuid>9c7c7d91-72f0-475b-a07d-2ccc5befcbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1dfecd5e-33ec-4332-86de-d088d6350b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0031W0007W0012&quot;,false]</value>
      <webElementGuid>1ecae13a-d3bb-40ad-ab56-f7a0acfd9de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012SELACTIVIDAD&quot;)</value>
      <webElementGuid>01c01e2f-dad8-4d0e-99af-0e274ca0f48a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='W0031W0007W0012SELACTIVIDAD']</value>
      <webElementGuid>c530aa20-e77b-4948-bcaa-536e8326d975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='W0031W0007W0012ACTIONCONTAINERTABLE_SELACTIVIDAD']/tbody/tr/td/img</value>
      <webElementGuid>cc610fc1-18ca-434a-955e-cdf60aa64e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sel Actividad']</value>
      <webElementGuid>2b32c4ff-0923-4916-a0f6-89d4c9d24b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/img</value>
      <webElementGuid>60a15796-b762-49d5-bc9e-31bddc61d1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/PortalSena16/static/Resources/prompt.png' and @id = 'W0031W0007W0012SELACTIVIDAD' and @alt = 'Sel Actividad' and @title = 'Seleccionar Actividad Económica']</value>
      <webElementGuid>d34837e2-bef2-4d7d-8f3f-d8bd9f00c2ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
