<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N Empleados_W0031W0007W0012EMPNUMEMP</name>
   <tag></tag>
   <elementGuidId>c78724fa-f6f2-496f-aa6d-db6d1a4dd50a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0031W0007W0012EMPNUMEMP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0031W0007W0012EMPNUMEMP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>302b7b4f-d42b-4d1b-ac9a-3430d5db4c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1cbfd6ea-b8fc-4347-a960-0c1a608500bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012EMPNUMEMP</value>
      <webElementGuid>213bc337-4448-489f-b6db-9c2feb310e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012EMPNUMEMP</value>
      <webElementGuid>f6814c8f-bd7d-49f3-a436-ff5d8b15be3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>858d8433-9469-4e62-bec2-5737580e0c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>-999999</value>
      <webElementGuid>d99198d3-2d75-4609-ae7e-cfe5eb131783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999999</value>
      <webElementGuid>084684d5-676c-4505-b837-41273c9c50d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>13b8ca8a-d8a0-4653-a2e8-2490fb00560a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>025cb791-4050-4e05-ac0f-d48a751eb511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn Attribute_Required form-control</value>
      <webElementGuid>85814528-3f1e-4be5-8a53-3aaa9f49043f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 86,'W0031W0007W0012',false,'',0)</value>
      <webElementGuid>0032c7ec-44e9-4610-a4ad-82db7fc5cfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.num.valid_integer( this,'.');;gx.evt.onchange(this, event)</value>
      <webElementGuid>9e5dc464-eec5-40a9-98b1-c570663f6d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>gx.num.valid_integer( this,'.');;gx.evt.onblur(this,86);</value>
      <webElementGuid>5f61f61a-e898-4e93-9a9c-3a9e014d5960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0031W0007W0012&quot;,false]</value>
      <webElementGuid>a5c356c7-101f-47e1-aad9-0c41fb6685fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3a867dd7-8fa7-4f65-a93e-cb4a5bc60abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>726b8a0a-3488-45cc-bbe2-4141b7567b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012EMPNUMEMP&quot;)</value>
      <webElementGuid>6bd1f950-d143-4673-8705-6b93a33bad78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0031W0007W0012EMPNUMEMP']</value>
      <webElementGuid>4997cc09-adf6-4766-8884-0a6b0aa647af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0031W0007W0012TABLEATTRIBUTESINFORMSECTION1']/div[12]/div/div/div/input</value>
      <webElementGuid>8ee26d39-c1b8-4c97-895b-26a5d46d8732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/input</value>
      <webElementGuid>7996d3b9-9cba-4a18-839a-d6ed374900d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'W0031W0007W0012EMPNUMEMP' and @name = 'W0031W0007W0012EMPNUMEMP']</value>
      <webElementGuid>24acd04a-21a3-4175-81d8-c0658d297ed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
