<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telfono_W0031W0007W0012EMPTEL</name>
   <tag></tag>
   <elementGuidId>aaa8c985-5d0d-41bb-9b84-b51d38c7cc93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0031W0007W0012EMPTEL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0031W0007W0012EMPTEL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e16a6a2-044c-4e6e-8b64-666b53ebd89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>1fd0af71-9ee2-4a04-8f78-bac158492dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012EMPTEL</value>
      <webElementGuid>417a8c33-236e-4735-b415-c2eb972ebcf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012EMPTEL</value>
      <webElementGuid>bb4a19dc-b49b-4899-94ed-1bfd0d153abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4eee3fd4-7df2-4940-b54b-6e28f5c2ce39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1d4b0bf-4643-42fb-aeaa-b3839f06369e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f3548755-a75e-4d6e-82c3-0095830e9cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn form-control</value>
      <webElementGuid>dcb55d8e-3748-4426-b2b1-05505a5aa597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 113,'W0031W0007W0012',false,'',0)</value>
      <webElementGuid>1a47cb81-a4b7-46a6-81bb-31e8f7fb7aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>11d9ec16-57c2-4860-b701-55df07eef062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,113);</value>
      <webElementGuid>5af05118-2656-4187-9ebc-59d1692be7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0031W0007W0012&quot;,false]</value>
      <webElementGuid>98f9c673-eff3-441a-b189-3945bc2ca845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bcf8a488-08e6-441c-8dfe-ca82861295d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012EMPTEL&quot;)</value>
      <webElementGuid>70f02584-5c58-4065-ac97-caa8b4815df4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0031W0007W0012EMPTEL']</value>
      <webElementGuid>f2408017-be7a-4239-9561-a50c53b75012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0031W0007W0012TABLEATTRIBUTESINFORMSECTION1']/div[15]/div/div/div/input</value>
      <webElementGuid>af40b53c-2645-4007-b068-5af5be465d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div/input</value>
      <webElementGuid>0fedf7fd-95f0-4667-a84d-a745ae14ff8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'W0031W0007W0012EMPTEL' and @name = 'W0031W0007W0012EMPTEL']</value>
      <webElementGuid>5dc844c9-e30b-4ea3-9bf0-a90ce71f940f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
