<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fax_W0031W0007W0012EMPFAX</name>
   <tag></tag>
   <elementGuidId>f192d412-b45a-4b4f-9ddc-b20bc7643ac4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0031W0007W0012EMPFAX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0031W0007W0012EMPFAX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1237ea49-cef7-456e-827a-99420986acf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>31d736eb-b6d2-4b4a-abe1-582ad62acf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012EMPFAX</value>
      <webElementGuid>cf30420c-ecce-4365-b94e-053ee3549fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012EMPFAX</value>
      <webElementGuid>7b21077a-a3e0-40e1-a61f-7020f1c727f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4e1dff5d-6ab7-421e-8c24-d7f545c0ea4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1fe480ee-c1cc-4878-84c3-e49bd03f71d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c03fb6dc-c478-4c83-bd92-a47f617dce82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn form-control</value>
      <webElementGuid>95630679-fd95-4fac-9e8c-e39758f0427d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 122,'W0031W0007W0012',false,'',0)</value>
      <webElementGuid>351d4fd2-5c0e-4a8b-bb4c-59080f6f8ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>5cd288db-1ea6-4996-8dd3-08135cae73ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,122);</value>
      <webElementGuid>c042659e-0f78-4406-a3bb-7d30a11a2099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0031W0007W0012&quot;,false]</value>
      <webElementGuid>2638f7bf-69df-418b-b73b-c0b255a1ee78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>10bff952-6877-4fe9-b91b-2d5675ef31f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012EMPFAX&quot;)</value>
      <webElementGuid>45de710e-55f2-4f03-91a8-fbcd91ab4f6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0031W0007W0012EMPFAX']</value>
      <webElementGuid>c3e9cda5-140a-4e4c-b1bf-003eda1ddb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0031W0007W0012TABLEATTRIBUTESINFORMSECTION1']/div[16]/div/div/div/input</value>
      <webElementGuid>907c8439-d97b-4483-80a9-98bb3983669c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/input</value>
      <webElementGuid>7ae09a2b-647f-434f-951f-8be74c0d5130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'W0031W0007W0012EMPFAX' and @name = 'W0031W0007W0012EMPFAX']</value>
      <webElementGuid>057f991f-cb72-42c7-a5b9-841151e49d18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
