<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nro. Identificacin_W0031W0007W0012EMPNUMID</name>
   <tag></tag>
   <elementGuidId>e38c59df-a970-4ae2-b68b-d2bda258e073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0031W0007W0012EMPNUMID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0031W0007W0012EMPNUMID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a805ed3a-614b-4701-a10d-0f945b353e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8be620a9-f0db-4625-b3c3-e9ca00a37001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012EMPNUMID</value>
      <webElementGuid>23f0d13b-2e91-477f-9e75-ea5c415a06e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012EMPNUMID</value>
      <webElementGuid>2108df4b-1edb-48e5-8ed8-e0b7b73ddb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e9c11529-a434-47be-b113-1894b3276971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>acec992f-3431-449a-8f3a-38e8dfb79cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>43c864ea-7ebe-4323-bd46-c34c8c74d2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn Attribute_Required form-control</value>
      <webElementGuid>06af1c39-2576-4116-bd46-e763e6ab4597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 61,'W0031W0007W0012',false,'',0)</value>
      <webElementGuid>a7839718-2b8e-4b24-8ded-71a4810f860e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.value=this.value.toUpperCase();;gx.evt.onchange(this, event)</value>
      <webElementGuid>fd37546b-b172-4367-9347-253ab704f972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>this.value=this.value.toUpperCase();;gx.evt.onblur(this,61);</value>
      <webElementGuid>d0f36103-f9a3-4dab-9a7a-a7374563a6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0031W0007W0012&quot;,false]</value>
      <webElementGuid>b18ce8fb-72bb-46c4-88f1-729f33b1c746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bcaecc3b-7bd2-4575-bca8-1014175b2f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012EMPNUMID&quot;)</value>
      <webElementGuid>d46e8a8e-9dd7-4d3e-ac20-03a7b23c59ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0031W0007W0012EMPNUMID']</value>
      <webElementGuid>1556b47c-d3ed-4d86-a86a-3fc560ad2173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0031W0007W0012TABLEATTRIBUTESINFORMSECTION1']/div[9]/div/div/div/input</value>
      <webElementGuid>84447eb1-3ff8-4094-bb26-cd5bed754355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/input</value>
      <webElementGuid>bcd2f7cc-e813-4d16-99ba-b24608ab52e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'W0031W0007W0012EMPNUMID' and @name = 'W0031W0007W0012EMPNUMID']</value>
      <webElementGuid>044bb4ab-b703-48f3-9ceb-7643ad55c3ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
