<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.CENTRO DE INVESTIGACIN Y _015f4d</name>
   <tag></tag>
   <elementGuidId>c7011d54-4eed-4fca-9dc0-88701211d2a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0031W0007W0012TIPORGSEC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0031W0007W0012TIPORGSEC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7e3da8d0-6ef3-4ebf-b4d8-d085aefbf707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012TIPORGSEC</value>
      <webElementGuid>bb949f61-6df1-4cc4-9dc8-c5d8470510fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012TIPORGSEC</value>
      <webElementGuid>21e3b900-895e-489c-940f-85d37785de36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn form-control</value>
      <webElementGuid>0446c3c0-697b-496f-8123-d173b0e570c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>65b2e80d-1355-46fa-845b-a41bee0e84d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 166,'W0031W0007W0012',false,'',0)</value>
      <webElementGuid>275e04e5-0a29-47ab-9c61-b70ac8df6593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>8cd52dfa-4160-4c89-85cf-35f888adab19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,166);</value>
      <webElementGuid>ef142f04-39a2-4721-9fb5-3963b78b3829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3d8b6f24-05a8-4748-8bc3-0eaec1eb86ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1b57679b-78ea-401a-a6e7-870c5291f990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Seleccione...CENTRO DE INVESTIGACIÓN Y DESARROLLO TECNOLÓGICO EN TEMAS RELACIONADOS CON EL SECTOREDUCACIÓN MEDIAENTIDADES DE FORMACIÓN PARA EL TRABAJO Y DESARROLLO HUMANOINSTITUCIONES DE EDUCACIÓN SUPERIOR Y UNIVERSIDADES</value>
      <webElementGuid>eaf02fa2-2bb8-49c5-950e-f042e179feb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012TIPORGSEC&quot;)</value>
      <webElementGuid>8d507ba4-1fff-49f1-94da-f62e246a4ec3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0031W0007W0012TIPORGSEC']</value>
      <webElementGuid>8a6c476d-aee9-4fb9-800c-902a990fe092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0031W0007W0012TABLEATTRIBUTESINFORMSECTION1']/div[19]/div[2]/div/div/select</value>
      <webElementGuid>bfa452e7-0294-4756-a431-18bc2deab801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo organización'])[1]/following::select[1]</value>
      <webElementGuid>4a7daef4-e8e5-4b84-b49b-162f5c782607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clasificación organización'])[1]/following::select[2]</value>
      <webElementGuid>12ab1831-adaa-4fc0-8e2b-27707302d9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Página web'])[1]/preceding::select[1]</value>
      <webElementGuid>9a5de5d7-a962-4d16-8ab2-d22c2fceed9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[1]/preceding::select[1]</value>
      <webElementGuid>033779cf-4528-485a-b421-e5617c844c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div[2]/div/div/select</value>
      <webElementGuid>e3401b62-7677-4f1f-b160-5e1bf093f84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0031W0007W0012TIPORGSEC' and @name = 'W0031W0007W0012TIPORGSEC' and (text() = '
Seleccione...CENTRO DE INVESTIGACIÓN Y DESARROLLO TECNOLÓGICO EN TEMAS RELACIONADOS CON EL SECTOREDUCACIÓN MEDIAENTIDADES DE FORMACIÓN PARA EL TRABAJO Y DESARROLLO HUMANOINSTITUCIONES DE EDUCACIÓN SUPERIOR Y UNIVERSIDADES' or . = '
Seleccione...CENTRO DE INVESTIGACIÓN Y DESARROLLO TECNOLÓGICO EN TEMAS RELACIONADOS CON EL SECTOREDUCACIÓN MEDIAENTIDADES DE FORMACIÓN PARA EL TRABAJO Y DESARROLLO HUMANOINSTITUCIONES DE EDUCACIÓN SUPERIOR Y UNIVERSIDADES')]</value>
      <webElementGuid>d3db51d0-3d7d-4c04-bbca-61410aeb4345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
