<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Razon Social_W0031W0007W0012EMPRAZSOC</name>
   <tag></tag>
   <elementGuidId>a889adee-c18b-455f-8961-55f9c91db5f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0031W0007W0012EMPRAZSOC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='W0031W0007W0012EMPRAZSOC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>789616ad-1fc7-42a3-9783-5cd4922dd5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b2deb37-b12a-445d-a1c8-90ce7300cc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>c75aebfa-1715-4795-a36b-6cc642788bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d1164e01-bfd8-404a-b173-399148211345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012EMPRAZSOC</value>
      <webElementGuid>e9838418-9132-476e-b70c-40c42e092420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012EMPRAZSOC</value>
      <webElementGuid>ae8a0d4e-4d2d-42ba-943c-e787f647ca80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 77,'W0031W0007W0012',false,'',0)</value>
      <webElementGuid>bf7f4ce1-5b7b-4dd9-9cb1-cf8ee8d77700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.value=this.value.toUpperCase();;gx.evt.onchange(this, event)</value>
      <webElementGuid>817361ba-bb25-4dac-8fd2-0ad7dfbc23f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>this.value=this.value.toUpperCase();;gx.evt.onblur(this,77);</value>
      <webElementGuid>cb0b5e6d-0c29-4b94-8504-272511b7c9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn Attribute_Required form-control</value>
      <webElementGuid>a1a9c100-a72e-47be-b8b8-3a2d382726d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return gx.evt.checkMaxLength(this,256,event);</value>
      <webElementGuid>924ff891-cece-4ba9-b35b-e30124e93b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>return gx.evt.checkMaxLength(this,256,event);</value>
      <webElementGuid>3c3a1be2-f97e-410f-8f66-15ed0600fb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msk-att</name>
      <type>Main</type>
      <value>maxlength</value>
      <webElementGuid>96737ba2-f886-410d-af73-9f74591a80ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>d9cab8f6-028e-4d59-b5cb-d1337d5e5cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>3ac60938-cdd4-4aa2-afbe-a585d51adc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0031W0007W0012&quot;,false]</value>
      <webElementGuid>8460f587-100c-41a0-91ff-6c44d522cc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>604a7c21-cd7b-4666-ab38-542a3ff2f249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012EMPRAZSOC&quot;)</value>
      <webElementGuid>adaaa16d-1329-4026-83ca-2eb5076f1e2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='W0031W0007W0012EMPRAZSOC']</value>
      <webElementGuid>994ecd22-2181-444b-b779-6a57ab4f7c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0031W0007W0012TABLEATTRIBUTESINFORMSECTION1']/div[11]/div/div/div/textarea</value>
      <webElementGuid>0fed9abf-c952-4293-b991-9de7c3efb9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/textarea</value>
      <webElementGuid>8dbc92a1-5108-4882-9f9a-5c266ae9d071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'W0031W0007W0012EMPRAZSOC' and @id = 'W0031W0007W0012EMPRAZSOC']</value>
      <webElementGuid>a8f6a413-b1bd-4688-a293-cf0a1e13906d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
