<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Informacin Adicional Requerida_gxp0_ifrm</name>
   <tag></tag>
   <elementGuidId>61b7cf6c-d736-477a-bfd6-82e813fd2d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gxp0_ifrm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gxp0_ifrm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b01dc914-8447-4d1e-af92-036f46cbbaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gxp0_ifrm</value>
      <webElementGuid>683207d9-79d3-49c6-8e52-023a3aee16e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://172.29.35.250:8080/PortalSena16/servlet/com.portalsena.wpcamposparametrizados?0,INS,gxPopupLevel%3D0%3B</value>
      <webElementGuid>fa6399a7-3738-481d-85b2-5c2bc6580622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Com.portalsena</value>
      <webElementGuid>acea02fc-d6bb-4c55-865e-3b5708f234ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gxp0_ifrm&quot;)</value>
      <webElementGuid>b7e8f006-4ca5-48be-b411-21e4ff712e18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gxp0_ifrm']</value>
      <webElementGuid>d172d221-96e5-4c0b-873b-33eaec62153d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gxp0_c']/iframe</value>
      <webElementGuid>697e6c20-2dd3-43a4-a893-6578db92b87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f66a42fd-be63-47f4-a09e-9de34e8814c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'gxp0_ifrm' and @src = 'http://172.29.35.250:8080/PortalSena16/servlet/com.portalsena.wpcamposparametrizados?0,INS,gxPopupLevel%3D0%3B' and @title = 'Com.portalsena']</value>
      <webElementGuid>9b2f0d83-9c29-417c-ab96-0963cd3fe77d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
