<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Seleccin de Ocupacin de Candidato_gxp0_ifrm</name>
   <tag></tag>
   <elementGuidId>6216af1d-18f6-4e7e-8ddf-795a885c2a8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gxp0_ifrm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gxp0_ifrm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>df1b8f1f-ac49-4787-a6f5-ee841d04cd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gxp0_ifrm</value>
      <webElementGuid>a1a234f9-023a-44a8-a7c8-ae44b58247bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://172.29.35.250:8080/PortalSena16/servlet/com.portalsena.wpseleccionprofesionescandidato?INS,0,,,0,gxPopupLevel%3D0%3B</value>
      <webElementGuid>d6e5bd1f-b492-40e8-9fca-af47b6a970e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Com.portalsena</value>
      <webElementGuid>74bb7277-7d6f-4054-a2ab-c761d300edae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gxp0_ifrm&quot;)</value>
      <webElementGuid>6fa448b0-5171-4579-bdf5-684c986fd113</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gxp0_ifrm']</value>
      <webElementGuid>5ffab512-1dd6-40b0-9ef2-9cea088caaa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gxp0_c']/iframe</value>
      <webElementGuid>8876cec6-c57e-4a30-8fd9-5fe24c437cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f12dfa91-d056-4aae-8ca7-86cfacf34298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'gxp0_ifrm' and @src = 'http://172.29.35.250:8080/PortalSena16/servlet/com.portalsena.wpseleccionprofesionescandidato?INS,0,,,0,gxPopupLevel%3D0%3B' and @title = 'Com.portalsena']</value>
      <webElementGuid>3916566e-201f-493f-9f46-784dd5c6a904</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
