<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_reas Inters_gxp0_ifrm</name>
   <tag></tag>
   <elementGuidId>df40a3a5-b849-468e-b8cc-ac3b1099f66c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gxp0_ifrm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gxp0_ifrm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1de9fb40-0ed6-43fb-90b6-8dfd22b8cffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gxp0_ifrm</value>
      <webElementGuid>fff2d725-9e06-4d3e-aced-5b549276967e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://172.29.35.250:8080/PortalSena16/servlet/com.portalsena.wpcandidatosareasinteres?,,gxPopupLevel%3D0%3B</value>
      <webElementGuid>a8777fcd-a96a-4447-8a77-7c1ac42c1a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Com.portalsena</value>
      <webElementGuid>15a4dcb0-d080-4088-827f-1dc7082208f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gxp0_ifrm&quot;)</value>
      <webElementGuid>fdad8651-88ee-46cf-85cf-21688318017d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gxp0_ifrm']</value>
      <webElementGuid>da889e2a-83cf-4ffe-9b5e-e127e826b45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gxp0_c']/iframe</value>
      <webElementGuid>05888105-61c7-4a50-8b3f-aac4e1b475a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4d817340-78af-4c6a-9d26-4ab0937239ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'gxp0_ifrm' and @src = 'http://172.29.35.250:8080/PortalSena16/servlet/com.portalsena.wpcandidatosareasinteres?,,gxPopupLevel%3D0%3B' and @title = 'Com.portalsena']</value>
      <webElementGuid>3819bd1a-839e-4ef8-b3d1-059d1cbf3796</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
