<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ocupacin(es)_W0026W0007W0012SELCARGOS</name>
   <tag></tag>
   <elementGuidId>5bd8328b-65a2-47e2-a18a-5afd45ff676f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='W0026W0007W0012SELCARGOS']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012SELCARGOS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5dd31d06-6df3-4c03-9b68-5c178e98fb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/PortalSena16/static/Resources/ActionDisplay.png</value>
      <webElementGuid>2cbced56-9d84-48e1-9c53-d93f497f1ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>7993c25e-1439-47f8-b6c8-3b5c577729a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012SELCARGOS</value>
      <webElementGuid>efad4eb8-41fd-4d2f-9d8a-e714b5de1787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Indique el(los) Cargos(s) del Candidato</value>
      <webElementGuid>f9323a5f-2d93-4895-98b7-79e3565ab7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Indique el(los) Cargos(s) del Candidato</value>
      <webElementGuid>3780f1f2-70fe-4773-a806-503920796cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 196,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>85a5ff41-562f-4511-b4f6-b6b10207c4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt-control</name>
      <type>Main</type>
      <value>SELCARGOS</value>
      <webElementGuid>967f4055-5023-44b1-b666-56dbedccdeb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b12b7fb9-0afd-4d9d-8edf-4e04c4a58a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0026W0007W0012&quot;,false]</value>
      <webElementGuid>817c9428-acbd-4cd9-9394-bd5842a34050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012SELCARGOS&quot;)</value>
      <webElementGuid>07574a05-d7ec-4203-8054-4980348a95cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='W0026W0007W0012SELCARGOS']</value>
      <webElementGuid>1b4212e4-84f1-41bd-9757-d9aa6fbbaaee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012K2BTOOLSTABLE_ATTRIBUTECONTAINERDESCRIPCIONCARGOSFIELDCONTAINER']/img</value>
      <webElementGuid>4fe00c07-95c4-4be8-ba25-140d65dd19bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Indique el(los) Cargos(s) del Candidato']</value>
      <webElementGuid>b0134239-6e30-43b0-a58b-b5772a3be3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/fieldset/div/div/div/div/div/div[2]/div/img</value>
      <webElementGuid>48c85a77-9f2c-45c7-a5ee-f6d11f2141bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/PortalSena16/static/Resources/ActionDisplay.png' and @id = 'W0026W0007W0012SELCARGOS' and @alt = 'Indique el(los) Cargos(s) del Candidato' and @title = 'Indique el(los) Cargos(s) del Candidato']</value>
      <webElementGuid>6659c63b-5036-4461-a47b-74fa9c49d3c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
