<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_reas de Inters_W0026W0007W0012SELAREASINTERES</name>
   <tag></tag>
   <elementGuidId>28425efb-2141-45c4-8cb1-cf6bf33b3470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012SELAREASINTERES</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/PortalSena16/static/Resources/ActionDisplay.png' and @id = 'W0031W0007W0012SELAREASINTERES' and @alt = 'Sel Areas Interes' and @title = 'Indique el(las) Área(s) de Interés']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='W0026W0007W0012SELAREASINTERES']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3ab6e10f-f028-4530-aef0-a0a1773e07a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/PortalSena16/static/Resources/ActionDisplay.png</value>
      <webElementGuid>0b83c7ad-0dfc-48d0-91df-63c31a2f8be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>0e9906b2-9f80-4077-bc87-fa1bfd85f1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012SELAREASINTERES</value>
      <webElementGuid>2ca5b3e5-5d3b-41f6-97f8-401ba0a6045f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sel Areas Interes</value>
      <webElementGuid>8c88ae2e-c411-4111-bf38-a4eafb2e215b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Indique el(las) Área(s) de Interés</value>
      <webElementGuid>a26e3c6b-9162-4623-a89c-d403b513270c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 312,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>6e1a862a-fcbf-46ee-85a2-4e1f66535a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt-control</name>
      <type>Main</type>
      <value>SELAREASINTERES</value>
      <webElementGuid>d167a2e0-3288-49a9-83de-8b37b08f8f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>54d8a3f4-1973-4bb3-9e76-caa72fb3f389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0031W0007W0012&quot;,false]</value>
      <webElementGuid>cf00c581-8ec0-4116-87b0-5281ae548cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012SELAREASINTERES&quot;)</value>
      <webElementGuid>a6b20c75-5f8c-4f70-b54f-0bde50d9ff3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='W0026W0007W0012SELAREASINTERES']</value>
      <webElementGuid>a05da1af-319f-4211-b2e8-7d8b28c74dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='W0026W0007W0012ACTIONCONTAINERTABLE_SELAREASINTERES']/tbody/tr/td/img</value>
      <webElementGuid>251e6a9d-6dc3-4b47-900d-5b0245f00431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sel Areas Interes']</value>
      <webElementGuid>85be1dc0-af17-4b7c-98fc-a065c1391ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/img</value>
      <webElementGuid>091d4704-0732-4df1-8602-19ac2541022a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/PortalSena16/static/Resources/ActionDisplay.png' and @id = 'W0026W0007W0012SELAREASINTERES' and @alt = 'Sel Areas Interes' and @title = 'Indique el(las) Área(s) de Interés']</value>
      <webElementGuid>7af9d829-b563-4bd1-bdfc-d2a7b6890851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
