<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_reas de Inters_W0026W0007W0012SELAREASINTERES</name>
   <tag></tag>
   <elementGuidId>28425efb-2141-45c4-8cb1-cf6bf33b3470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='W0026W0007W0012SELAREASINTERES']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012SELAREASINTERES</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b7aac0a5-3fe2-4aa8-96c7-cee62c35df5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/PortalSena16/static/Resources/ActionDisplay.png</value>
      <webElementGuid>6b0fe1a3-1fb8-49aa-b574-adcbd40cb835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>acc09f4b-7eed-47e3-bfd5-21b04a8565eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012SELAREASINTERES</value>
      <webElementGuid>2d776080-6734-423c-9192-1c82b61254d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sel Areas Interes</value>
      <webElementGuid>3b43dddd-04d8-44e0-917c-d27b42bafe3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Indique el(las) Área(s) de Interés</value>
      <webElementGuid>6f74d94f-e836-4cf1-a747-afaa10c8d359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 312,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>882d3ae3-4b83-4f4d-8b98-6b1eec34b4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt-control</name>
      <type>Main</type>
      <value>SELAREASINTERES</value>
      <webElementGuid>60549d39-fb76-4ded-9130-f56f2b69d66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>52a9c583-0f12-4ca2-b439-772cbabaeda8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0026W0007W0012&quot;,false]</value>
      <webElementGuid>7898bf32-da8a-42e4-8fc7-2dd0d2cea398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012SELAREASINTERES&quot;)</value>
      <webElementGuid>3257b469-e563-453b-9e61-bd095a28b756</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='W0026W0007W0012SELAREASINTERES']</value>
      <webElementGuid>83f48ebf-d882-4bc4-8817-0d3c4ee5db76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='W0026W0007W0012ACTIONCONTAINERTABLE_SELAREASINTERES']/tbody/tr/td/img</value>
      <webElementGuid>355a983a-3cf4-490b-8ade-7d2802e7b007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sel Areas Interes']</value>
      <webElementGuid>32643f04-fab1-44e4-bacb-697e5e6e6527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/img</value>
      <webElementGuid>ec3af575-656a-4007-8b7b-1dc4806d2351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/PortalSena16/static/Resources/ActionDisplay.png' and @id = 'W0026W0007W0012SELAREASINTERES' and @alt = 'Sel Areas Interes' and @title = 'Indique el(las) Área(s) de Interés']</value>
      <webElementGuid>d12002ef-d754-4e14-ba8d-beb9610743a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
