<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ocupacin(es)_W0026W0007W0012SELCARGOS</name>
   <tag></tag>
   <elementGuidId>5bd8328b-65a2-47e2-a18a-5afd45ff676f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012SELCARGOS</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/PortalSena16/static/Resources/ActionDisplay.png' and @id = 'W0031W0007W0012SELCARGOS' and @alt = 'Indique el(los) Cargos(s) del Candidato' and @title = 'Indique el(los) Cargos(s) del Candidato']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='W0026W0007W0012SELCARGOS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cdcd344f-3ad8-405c-9828-c728240707c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/PortalSena16/static/Resources/ActionDisplay.png</value>
      <webElementGuid>898ca901-63e8-4914-95ca-7235535dc797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>6a873735-12d4-4768-b26f-ac477d8b2f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012SELCARGOS</value>
      <webElementGuid>318a4099-b279-4202-ac1e-55895fb9ca23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Indique el(los) Cargos(s) del Candidato</value>
      <webElementGuid>c7197f22-64d7-421f-8bfe-4daff7e9bbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Indique el(los) Cargos(s) del Candidato</value>
      <webElementGuid>8d3d060a-87a9-4924-a315-bbbf923fdc0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 196,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>cb99b861-7d56-4b47-a151-6bbc1daaa9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt-control</name>
      <type>Main</type>
      <value>SELCARGOS</value>
      <webElementGuid>6ef9a2d1-39cc-42eb-a292-066b5320c9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5e06dd48-6c51-4f13-a824-ddc8f7e6133c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0031W0007W0012&quot;,false]</value>
      <webElementGuid>a19e6af1-1fbb-4508-9086-e03af05d9e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012SELCARGOS&quot;)</value>
      <webElementGuid>5e2130a6-1a1e-4321-985d-45451dd7b9ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='W0026W0007W0012SELCARGOS']</value>
      <webElementGuid>de84d0a2-ffd1-45a3-9d2a-eeaa99814eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012K2BTOOLSTABLE_ATTRIBUTECONTAINERDESCRIPCIONCARGOSFIELDCONTAINER']/img</value>
      <webElementGuid>e2558c65-143d-47b3-b636-009bb8045dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Indique el(los) Cargos(s) del Candidato']</value>
      <webElementGuid>5e794cb0-a900-49a2-b7b7-52cfadca8e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/fieldset/div/div/div/div/div/div[2]/div/img</value>
      <webElementGuid>24c64514-2779-4998-a6a4-e123b8217a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/PortalSena16/static/Resources/ActionDisplay.png' and @id = 'W0026W0007W0012SELCARGOS' and @alt = 'Indique el(los) Cargos(s) del Candidato' and @title = 'Indique el(los) Cargos(s) del Candidato']</value>
      <webElementGuid>f1736b91-029a-468b-af50-23aa1f868e06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
