<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Expedicin_W0026W0007W0012ECANFECEXPDOC</name>
   <tag></tag>
   <elementGuidId>ee94533e-2cb5-446f-9579-02695a2295df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANFECEXPDOC</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012ECANFECEXPDOC&quot;)[count(. | //*[@type = 'text' and @id = 'W0031W0007W0012ECANFECEXPDOC' and @name = 'W0031W0007W0012ECANFECEXPDOC']) = count(//*[@type = 'text' and @id = 'W0031W0007W0012ECANFECEXPDOC' and @name = 'W0031W0007W0012ECANFECEXPDOC'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0026W0007W0012ECANFECEXPDOC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>102861f0-c7ba-4821-b740-a9e9d9e96e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d6a6c35-4dc4-4f8b-83ae-a2c8ff951ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANFECEXPDOC</value>
      <webElementGuid>ce883828-65c1-42e8-9a3a-a9f378cca2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANFECEXPDOC</value>
      <webElementGuid>860fdd5d-3219-43ca-a470-25083239b190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>  /  /    </value>
      <webElementGuid>05898e1a-1cea-4231-8a73-0fa694066c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e743b1bb-641d-4ce2-a143-e9ee5310f6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c442ba81-16e7-4c6c-aa4a-8f4799357778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e7410785-8e7f-49c1-aa42-6c30530c7c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_TrnDate form-control</value>
      <webElementGuid>f9ba17fb-e045-46e4-816b-a68de879ea6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 94,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>684842f8-a5cf-4808-a6e5-d599260e52a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.date.valid_date(this, 10,'DMY',0,24,'spa',false,0);;gx.evt.onchange(this, event)</value>
      <webElementGuid>de0ff549-ef2f-43f4-9f85-69aa55bc8a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>gx.date.valid_date(this, 10,'DMY',0,24,'spa',false,0);;gx.evt.onblur(this,94);</value>
      <webElementGuid>5d53544e-47b6-43cc-8ad1-187b960f006d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0031W0007W0012&quot;,false]</value>
      <webElementGuid>d26269f7-edd1-405e-9aec-7348de88c7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2780b414-739e-4973-a6f6-b4ac5645273f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ECANFECEXPDOC&quot;)</value>
      <webElementGuid>cc004892-7741-468d-87ea-524c7fa53964</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0026W0007W0012ECANFECEXPDOC']</value>
      <webElementGuid>f91d4f85-d122-4d3e-85b1-be978fa5163b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012ECANFECEXPDOC_dp_container']/div/input</value>
      <webElementGuid>d4de738c-eb64-455f-8356-b1022447bef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/div/input</value>
      <webElementGuid>3e62ca51-1fda-48f0-b35b-38f8ad431e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'W0026W0007W0012ECANFECEXPDOC' and @name = 'W0026W0007W0012ECANFECEXPDOC']</value>
      <webElementGuid>425c1e1e-bbae-4313-8d40-a225e0b702f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
