<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Celular_W0026W0007W0012ECANCEL</name>
   <tag></tag>
   <elementGuidId>70135505-abd0-421d-a7c3-eb7bd4dadd62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANCEL</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'tel' and @id = 'W0031W0007W0012ECANCEL' and @name = 'W0031W0007W0012ECANCEL']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0026W0007W0012ECANCEL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53db1dd8-f5d7-47c4-9d17-2b24a38d80ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>719f057e-5581-4c82-86cf-7aadd8e993a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANCEL</value>
      <webElementGuid>9107ffda-da60-402d-859e-6a35f17242ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANCEL</value>
      <webElementGuid>e3c7eede-3268-4f45-aaa8-d0290d76beaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>9d7cc550-563e-4781-ac8f-3ccf27170364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>14081d6c-d2d7-403e-9e65-8c3934e1f7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>45d6cb07-699b-4e0d-9eb1-2fe2bf128556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>d76f5cfd-4ae6-4794-ad89-c5d3f95ae9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 272,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>8daf8cf6-63c9-4282-8e34-76599042cd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>fd09d8a2-ab6a-4c37-bf8b-8aef1b666118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,272);</value>
      <webElementGuid>736e3695-c052-4272-a5f8-b52f14a8b086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0031W0007W0012&quot;,false]</value>
      <webElementGuid>59adfb30-468b-4d33-b2f2-be31ffc83960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d0508674-7e06-4517-8686-e1a1d92c0f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ECANCEL&quot;)</value>
      <webElementGuid>25ff2825-0469-4414-a3f6-80a974b16d34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0026W0007W0012ECANCEL']</value>
      <webElementGuid>c438173f-42e4-4870-a7d6-c9370cbc0e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP3TABLECONTENT']/div[4]/div[2]/div/div/input</value>
      <webElementGuid>16d411f2-3285-4c0b-9de3-87303910c4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>bd75fbab-f379-4407-ab2a-1220771a3bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'W0026W0007W0012ECANCEL' and @name = 'W0026W0007W0012ECANCEL']</value>
      <webElementGuid>b9bfddd4-d3e5-4ef3-8275-ca2dd3780421</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
