<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_reas de Inters_CONFIRMAR</name>
   <tag></tag>
   <elementGuidId>b62ee805-8073-4974-b2f5-e281022d606b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CONFIRMAR']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CONFIRMAR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a328260f-2d40-481e-89d6-51698ba0d0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d23a26d4-6fc9-43d7-b235-fc841125833f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CONFIRMAR</value>
      <webElementGuid>b6d2147d-5a11-40c2-9c6c-688a8d141008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CONFIRMAR</value>
      <webElementGuid>7447b8a4-e9a6-437b-9f31-3bd3022f98cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>7bbba34b-d8f0-448e-8e3d-f78b24921e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>K2BToolsButton_MainAction btn btn-default</value>
      <webElementGuid>fb3654d1-77a6-4e00-8db4-210885e89d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d73c51b3-a792-481b-9d89-494b84119b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 38,'',false,'',0)</value>
      <webElementGuid>7b6f19ae-cc26-4194-8b6c-4c9c2670f90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt-control</name>
      <type>Main</type>
      <value>CONFIRMAR</value>
      <webElementGuid>c04c5cdb-7caa-4c04-93b0-1cd86624b594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;&quot;,false]</value>
      <webElementGuid>61a53dac-ee20-452c-a921-f588c0e6b3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxhiddenonchange</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>8c4e7dc7-d8ff-4a7b-a6ce-2869e672f6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aef7f800-abcb-4555-815a-07b661626733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CONFIRMAR&quot;)</value>
      <webElementGuid>ed093354-27bb-47a0-91ac-e659cc593999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Crear Candidatos/Page_Candidatos/iframe_reas Inters_gxp0_ifrm</value>
      <webElementGuid>0695feb8-22b2-4e84-b17b-cb27b9522d6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CONFIRMAR']</value>
      <webElementGuid>b9309233-c51a-462a-b226-9430b7d47c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ACTIONS_GRIDAREASCLAVE_GRIDASSOCIATEDLEFT']/tbody/tr/td/input</value>
      <webElementGuid>e4388a6f-8758-4c75-af53-5bf83541159c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>90b59cdf-c53c-40da-997d-f0f92dc86fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'CONFIRMAR' and @id = 'CONFIRMAR']</value>
      <webElementGuid>5de5405c-4312-48c8-b5fd-370194564585</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
