<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Segundo Nombre_W0026W0007W0012ECANNOMSEG</name>
   <tag></tag>
   <elementGuidId>f5c744e5-ce18-471e-8b1b-dcd731d77821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANNOMSEG</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012ECANNOMSEG&quot;)[count(. | //*[@type = 'text' and @id = 'W0031W0007W0012ECANNOMSEG' and @name = 'W0031W0007W0012ECANNOMSEG' and @data-gx-context = '[&quot;W0031W0007W0012&quot;,false]']) = count(//*[@type = 'text' and @id = 'W0031W0007W0012ECANNOMSEG' and @name = 'W0031W0007W0012ECANNOMSEG' and @data-gx-context = '[&quot;W0031W0007W0012&quot;,false]'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0031W0007W0012ECANNOMSEG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>507ab810-b194-4071-9d62-7a488518952b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad898da4-b310-41f0-a480-d214b45a7ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANNOMSEG</value>
      <webElementGuid>e03e0f8f-62dc-472d-a844-82e73e08620e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANNOMSEG</value>
      <webElementGuid>78124c7e-987e-40bd-b8e9-10a32ce537fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>300892c4-0055-4508-8108-af5bbd58c1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>409c0c75-5f15-46c1-824b-5158a52c38e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>89b0bc26-835a-457f-b3c9-acadffdb9370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>0b3d319c-f017-477d-880a-df20e25b59de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 54,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>048bf4f4-0eb1-48f4-b50a-a404006085dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>8faf47aa-106b-426a-b3c2-d0172bbf5648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,54);</value>
      <webElementGuid>19513f88-c8a0-4c36-90d5-8c0cd92b5cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0031W0007W0012&quot;,false]</value>
      <webElementGuid>8b7cd7a8-cbea-44e1-a380-27dc29ba9680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>faded822-3b0f-4026-a5ee-5215227bc578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ECANNOMSEG&quot;)</value>
      <webElementGuid>e231756d-5958-435b-a8b4-1fa9193b0886</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0026W0007W0012ECANNOMSEG']</value>
      <webElementGuid>3a1db9f3-6d07-4ca0-9f4f-ade37833c1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>3ade77c1-c781-407a-9a00-73ec7d6a0244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>5da0d687-cad8-43d7-8f84-4f8d80cf9c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'W0026W0007W0012ECANNOMSEG' and @name = 'W0026W0007W0012ECANNOMSEG']</value>
      <webElementGuid>ffb57ef6-3121-4d57-8509-fe007b46c33f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
