<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Expedicin_W0026W0007W0012ECANFECEXPDOC</name>
   <tag></tag>
   <elementGuidId>ee94533e-2cb5-446f-9579-02695a2295df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0026W0007W0012ECANFECEXPDOC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANFECEXPDOC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b7605d6-b778-4fa6-a0e3-fe1b7629c295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32092b93-a482-48e1-aca9-0a1eb0de2a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012ECANFECEXPDOC</value>
      <webElementGuid>2ff5491f-b1dd-47e2-ba06-bc783e76406b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012ECANFECEXPDOC</value>
      <webElementGuid>d72adc7b-d82c-480f-ae3e-daea49f16aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>  /  /    </value>
      <webElementGuid>c44d0354-6660-482a-8a4d-b6caa8a61645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>b76ffa50-a4e7-4c69-a37e-3fe409fb721a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b5a2f2db-79a0-4dc5-ad99-db0445751450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>fa278ef7-eb36-4fe3-8843-8bfddd0f7000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_TrnDate form-control</value>
      <webElementGuid>6f47303f-9df3-4b13-bc2b-ba448830605a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 94,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>8dfb2aa3-eb64-4520-b256-cf8d2fccb7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.date.valid_date(this, 10,'DMY',0,24,'spa',false,0);;gx.evt.onchange(this, event)</value>
      <webElementGuid>351a3759-abae-45ff-8665-c86bd7cd99da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>gx.date.valid_date(this, 10,'DMY',0,24,'spa',false,0);;gx.evt.onblur(this,94);</value>
      <webElementGuid>fe44c14a-f09c-43a1-b602-dbcde57055d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0026W0007W0012&quot;,false]</value>
      <webElementGuid>2d2f0f4f-36aa-4b5b-8a7f-3d3cf1f38d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f3c081e1-fc24-4c08-b8b4-538e229a581c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012ECANFECEXPDOC&quot;)</value>
      <webElementGuid>a80012d7-2916-45af-813e-3da9b6df1284</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0026W0007W0012ECANFECEXPDOC']</value>
      <webElementGuid>148c968b-de40-4035-97f9-ea5282c03cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012ECANFECEXPDOC_dp_container']/div/input</value>
      <webElementGuid>aafef8e8-b612-488b-8d66-8a4388725689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/div/input</value>
      <webElementGuid>986f6466-68d6-4737-8ce0-18329a8d4022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'W0026W0007W0012ECANFECEXPDOC' and @name = 'W0026W0007W0012ECANFECEXPDOC']</value>
      <webElementGuid>bd5596c3-1c94-4a9a-ac26-f5b5404d7b4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
