<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero Identificacin_W0026W0007W0012EC_03770d</name>
   <tag></tag>
   <elementGuidId>43f44490-5568-4403-98c9-073f9f50edf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANNUMIDE</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012ECANNUMIDE&quot;)[count(. | //*[@type = 'text' and @id = 'W0031W0007W0012ECANNUMIDE' and @name = 'W0031W0007W0012ECANNUMIDE']) = count(//*[@type = 'text' and @id = 'W0031W0007W0012ECANNUMIDE' and @name = 'W0031W0007W0012ECANNUMIDE'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0026W0007W0012ECANNUMIDE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df9ed317-2da3-49b9-9eb9-b809b41ad57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>106ff86b-4d5e-4a6a-90c2-e50869ddb224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANNUMIDE</value>
      <webElementGuid>243f5827-33cf-47fa-b084-721b8cefaee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANNUMIDE</value>
      <webElementGuid>007ca9e2-8ebe-48bf-b28f-4010bdd2fde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e8c59774-0e88-49b1-be56-bfe98c517b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>61973e7e-3090-43a4-ac00-3fc86140dd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>d8c44e62-11b7-4d81-b7da-d17c840b7c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>a9e14e0c-ed5b-4137-871a-124cb6a6a52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 45,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>f6e23c28-e80e-497d-bdbd-3e66a8a53c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.value=this.value.toUpperCase();;gx.evt.onchange(this, event)</value>
      <webElementGuid>38fa6b0f-3045-41b9-b40b-4061596cbbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>this.value=this.value.toUpperCase();;gx.evt.onblur(this,45);</value>
      <webElementGuid>098ce5f8-3b6a-44cb-ad82-db1ceaaf117c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0026W0007W0012&quot;,false]</value>
      <webElementGuid>9728f4c3-ea2e-4f0a-8321-a74a25352c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1bd17d13-031e-4a66-996e-626fdabd191a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ECANNUMIDE&quot;)</value>
      <webElementGuid>7aae9a62-9ad4-41f6-8d0b-9f7c7cb66412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0026W0007W0012ECANNUMIDE']</value>
      <webElementGuid>6d2a835b-9b6e-494c-bd7a-1b1414461a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div/div[3]/div/div/input</value>
      <webElementGuid>a192d455-099a-4da5-95ec-7e1873121b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>4536ea3f-22fd-472b-abac-d28b69db8fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'W0026W0007W0012ECANNUMIDE' and @name = 'W0026W0007W0012ECANNUMIDE']</value>
      <webElementGuid>617eb7f4-190f-4563-9f27-6b44d4ff88a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
