<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Debe dar clic en el botn para diligen_16224f</name>
   <tag></tag>
   <elementGuidId>f19c1ceb-78a0-40f9-b84a-a45700f55f12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0026W0007W0012REGISTRARINFORMACION']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012REGISTRARINFORMACION</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a94ec28d-925a-41cb-8b84-a8b34885f7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7163d08a-4c07-411a-ba2b-0ab5c0113dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012REGISTRARINFORMACION</value>
      <webElementGuid>d4b53626-2304-454c-8d49-db0504006c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012REGISTRARINFORMACION</value>
      <webElementGuid>3e8e8ebb-e9e1-466e-b10b-ec8356574e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Registrar Información</value>
      <webElementGuid>d1ae163a-0e6b-416f-a16b-63f79ae709e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>K2BToolsButton_MainAction btn btn-default</value>
      <webElementGuid>79b43f6e-70e7-418c-ad36-8d4887cfc8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>7899ee62-2e46-46f6-9d67-a5efd0eba07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 232,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>c07936e2-969a-4e26-be97-ee7dc7e3799f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt-control</name>
      <type>Main</type>
      <value>REGISTRARINFORMACION</value>
      <webElementGuid>9c464b55-940f-4372-8a03-6467acd5f277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0026W0007W0012&quot;,false]</value>
      <webElementGuid>69b810a5-99d8-417a-a7bf-f16160aed2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012REGISTRARINFORMACION&quot;)</value>
      <webElementGuid>d2407a02-a869-41ac-98af-13e415b2a880</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0026W0007W0012REGISTRARINFORMACION']</value>
      <webElementGuid>617d24a9-82e9-41f5-a364-d02defee6e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012K2BTOOLSTABLE_ATTRIBUTECONTAINERLABELINFOADICIONALFIELDCONTAINER']/input</value>
      <webElementGuid>5d256cfd-5250-413a-82c2-7b66be2d2f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>6259a8bf-2acb-4ba4-89a5-4e87d821b4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'W0026W0007W0012REGISTRARINFORMACION' and @id = 'W0026W0007W0012REGISTRARINFORMACION']</value>
      <webElementGuid>6e370683-e467-4f22-9d31-998d777ea439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
