<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telfono_W0026W0007W0012ECANTEL</name>
   <tag></tag>
   <elementGuidId>48d02f9a-ef39-4294-b8f8-49c4fdc13e20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0026W0007W0012ECANTEL']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANTEL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8e0ad34-bf3d-4092-b774-e0a18ce122bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>77ca843d-24d9-47a4-9262-e25855105a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012ECANTEL</value>
      <webElementGuid>62321acd-2937-4acc-ad20-23b5126c2c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012ECANTEL</value>
      <webElementGuid>ccab78b4-a253-4faf-b57e-bce1cbb248b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>bea05edc-9c47-464f-9ec8-e0e07b798337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e6395210-bc67-4371-b327-7e3d33b22912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f6239642-ba30-4448-a1d2-2f0a9b02c698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>b3fdffa3-cd69-4aa9-9520-60a419cb3512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 268,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>6dc4177c-8386-4cf8-b21e-8801e1cb8748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>04adc038-55c8-4b6c-acd5-c4f4c5a1e504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,268);</value>
      <webElementGuid>05c74953-4fb4-447c-a129-cb98264386f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0026W0007W0012&quot;,false]</value>
      <webElementGuid>b952e695-df18-4930-8dc3-2d77c70eeb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>87c60fd0-c7da-4688-84aa-4977a6788a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012ECANTEL&quot;)</value>
      <webElementGuid>85d10882-fcc7-44b1-b60d-942f07c16f8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0026W0007W0012ECANTEL']</value>
      <webElementGuid>c7e88fab-a572-4e04-82bf-b526ca03aca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP3TABLECONTENT']/div[4]/div/div/div/input</value>
      <webElementGuid>c4c61e4e-c1bb-4ba2-b52d-86c36339843e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>42ffbfe8-78cf-45a7-99e7-d01238388413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'W0026W0007W0012ECANTEL' and @name = 'W0026W0007W0012ECANTEL']</value>
      <webElementGuid>b2a2b06a-483e-470b-af56-72b8a22acb51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
