<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sin Asignar Profesiones_CONFIRMARSELECCION</name>
   <tag></tag>
   <elementGuidId>3a5966d4-ac5b-4539-b83f-31681fd578f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CONFIRMARSELECCION']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CONFIRMARSELECCION</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a215838b-e4f6-40c9-a193-16c912fbac06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e79a0fdc-716d-4518-a21a-452b4766523f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CONFIRMARSELECCION</value>
      <webElementGuid>2404cf74-5c96-4188-bc7f-c74fb13bd5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CONFIRMARSELECCION</value>
      <webElementGuid>4eb2ce8a-e542-4231-afb6-f0309ca99b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar Selección</value>
      <webElementGuid>1af3e394-20f6-4f24-9988-22aac6fc9c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>K2BToolsButton_MainAction btn btn-default</value>
      <webElementGuid>7d1112c7-66f8-4ba6-bf65-22e80611d830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>db6fc86f-3025-45de-920c-39bc209086ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 51,'',false,'',0)</value>
      <webElementGuid>ea8b97fa-e4e6-4f4a-9b60-36510871cf53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt-control</name>
      <type>Main</type>
      <value>CONFIRMARSELECCION</value>
      <webElementGuid>7e1bb9a4-87ea-4639-a936-75e4fa9834c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;&quot;,false]</value>
      <webElementGuid>e8fe79ca-65e0-45e1-b075-15dbbfbab173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxhiddenonchange</name>
      <type>Main</type>
      <value>Confirmar Selección</value>
      <webElementGuid>da8b7a08-5b1a-42dd-838c-3d0f6a8b56e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6057dff0-45d5-4cb8-ae68-5ae40a031ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CONFIRMARSELECCION&quot;)</value>
      <webElementGuid>d8e8f264-12c7-4c99-97f3-f10d18354d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Crear Candidatos/Page_Candidatos/iframe_Seleccin de Ocupacin de Candidato_gxp0_ifrm</value>
      <webElementGuid>c30156a4-0819-4255-aaa4-bceb0aabf1e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CONFIRMARSELECCION']</value>
      <webElementGuid>543f4ccc-8609-4d50-9fe1-1eb0f6780a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ACTIONS_GRIDCARGOS_GRIDASSOCIATEDLEFT']/tbody/tr/td[2]/input</value>
      <webElementGuid>992e9ee9-60a9-49dc-b1c8-4bd3db971756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>b269b3a9-2aca-418e-9501-8075e3fdec3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'CONFIRMARSELECCION' and @id = 'CONFIRMARSELECCION']</value>
      <webElementGuid>1704f5ae-687d-4812-a1d8-7547eea89276</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
