<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Debe dar clic en el botn para diligen_16224f</name>
   <tag></tag>
   <elementGuidId>f19c1ceb-78a0-40f9-b84a-a45700f55f12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012REGISTRARINFORMACION</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @name = 'W0031W0007W0012REGISTRARINFORMACION' and @id = 'W0031W0007W0012REGISTRARINFORMACION' and @data-gx-evt-control = 'REGISTRARINFORMACION']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0026W0007W0012REGISTRARINFORMACION']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ecf5176-c9c5-4e90-99e6-d69307a1471a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>398f426c-d536-4a7f-83bb-1758ceb97193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012REGISTRARINFORMACION</value>
      <webElementGuid>590257e4-3d69-4f57-99dc-8b4e2f93c21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012REGISTRARINFORMACION</value>
      <webElementGuid>d8f299f2-14ae-4791-b84e-5fe03d338d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Registrar Información</value>
      <webElementGuid>7c11e571-50f5-4db9-8a17-0fe869129cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>K2BToolsButton_MainAction btn btn-default</value>
      <webElementGuid>dff36bba-d746-4500-8026-9d35880b5f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>eb0ccb3a-d620-4a3e-acda-cc8413534f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 232,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>a4719f9d-f1eb-4403-9f6e-7a3a5e07c12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt-control</name>
      <type>Main</type>
      <value>REGISTRARINFORMACION</value>
      <webElementGuid>219a4803-425c-4d35-86ac-499ec71c93d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0031W0007W0012&quot;,false]</value>
      <webElementGuid>dcb7daa1-d4a3-4192-bc24-14d652dfcd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012REGISTRARINFORMACION&quot;)</value>
      <webElementGuid>af18638a-bdee-4c9a-932c-b48d3fa2400c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0026W0007W0012REGISTRARINFORMACION']</value>
      <webElementGuid>e0021906-5298-4219-98b9-4b2c7f714819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012K2BTOOLSTABLE_ATTRIBUTECONTAINERLABELINFOADICIONALFIELDCONTAINER']/input</value>
      <webElementGuid>7e697e72-a77d-41be-a164-04f7127d8bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>2c4842e6-c670-450b-a963-838cc3082c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'W0026W0007W0012REGISTRARINFORMACION' and @id = 'W0026W0007W0012REGISTRARINFORMACION']</value>
      <webElementGuid>a096331d-9fb1-489d-b261-874c03fc3158</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
