<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-        000000_W0026W0007W0012ENTER</name>
   <tag></tag>
   <elementGuidId>7225c618-2146-499a-b004-a03b8e11813f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0026W0007W0012ENTER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ENTER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfda1ffe-3317-4527-afda-40d38e29abf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cfb8cbb9-fbae-4881-93c9-883752b1ab9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012ENTER</value>
      <webElementGuid>dc7e3c47-735a-4b1e-905d-9bbc7e0940e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012ENTER</value>
      <webElementGuid>e66c0e26-385f-4946-a2e9-48144a54e97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>789162ce-4926-47cd-bf8f-4bbb0a3c7700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>376c748c-6c44-4e0e-91f4-713279140f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>K2BToolsButton_MainAction btn btn-default</value>
      <webElementGuid>17026e08-54ce-4342-9be3-4134f6c53c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>faead9c8-4d40-48d7-ae5c-f97454059557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 333,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>85dd776f-8ce6-41ee-b74a-2b8d30e59059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt-control</name>
      <type>Main</type>
      <value>ENTER</value>
      <webElementGuid>e24e78ee-c79b-42e4-9008-d367745e8ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0026W0007W0012&quot;,false]</value>
      <webElementGuid>ea6e6545-2f9d-4388-9a95-75110592269a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012ENTER&quot;)</value>
      <webElementGuid>929fe040-a6f6-4e0f-a072-e8bf96ae59ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0026W0007W0012ENTER']</value>
      <webElementGuid>985e432b-9384-4dc3-84f9-9449c18f1b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='W0026W0007W0012ACTIONSCONTAINERBUTTONS']/tbody/tr/td/input</value>
      <webElementGuid>1bd969c3-08c8-41c9-be66-feea4aea59ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>655f5799-5005-4144-8bc1-a359a31a9486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'W0026W0007W0012ENTER' and @id = 'W0026W0007W0012ENTER' and @title = 'Confirmar']</value>
      <webElementGuid>6e5176ff-eef9-4028-89b7-fd545758d760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
