<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clasificacin Nacional de Ocupaciones__a6b682</name>
   <tag></tag>
   <elementGuidId>0f6bb65c-5622-445e-96df-432c567e3162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vMULTIROWITEMSELECTED_GRIDCARGOS_0002']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vMULTIROWITEMSELECTED_GRIDCARGOS_0002</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd4c305c-0fd3-49da-8d0b-df84938fb7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vMULTIROWITEMSELECTED_GRIDCARGOS_0002</value>
      <webElementGuid>a9a7d36a-74ca-4575-b467-58fcecc573eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>09df223d-010e-4f32-adbc-1bc5460dad26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vMULTIROWITEMSELECTED_GRIDCARGOS_0002</value>
      <webElementGuid>5a1f79e2-416a-45a1-ae86-b19ee1213369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4706ff96-6577-4b8c-8374-92ef62b943d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 90,'',false,'0002',89)</value>
      <webElementGuid>0f69b769-15b4-4a46-882b-d92814fa111e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,90);</value>
      <webElementGuid>73543716-699e-493a-81c1-4c7b8fb26362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt-control</name>
      <type>Main</type>
      <value>vMULTIROWITEMSELECTED_GRIDCARGOS</value>
      <webElementGuid>b400db89-ec7c-4633-83e4-5f823147a459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;&quot;,false]</value>
      <webElementGuid>deebd970-1ee8-4a82-b9d0-ca4fcc005cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vMULTIROWITEMSELECTED_GRIDCARGOS_0002&quot;)</value>
      <webElementGuid>bafbb02a-508e-426d-9370-cd8d43fa7701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Crear Candidatos/Page_Candidatos/iframe_Seleccin de Ocupacin de Candidato_gxp0_ifrm</value>
      <webElementGuid>9b24da6b-2130-4acb-9958-9ffe370bfa2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vMULTIROWITEMSELECTED_GRIDCARGOS_0002']</value>
      <webElementGuid>cd4f5cea-12e4-4635-8fe3-c617ea9d346d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='GridcargosContainerRow_0002']/td/label/input</value>
      <webElementGuid>febded2e-9c3e-4d17-abe5-e9ba58d20f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/label/input</value>
      <webElementGuid>f5116c27-b099-43c7-9a48-921ed016f900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'vMULTIROWITEMSELECTED_GRIDCARGOS_0002' and @type = 'checkbox' and @name = 'vMULTIROWITEMSELECTED_GRIDCARGOS_0002']</value>
      <webElementGuid>30cbe756-ef1b-4b23-8a3d-a9d813805365</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
