<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.CASADOINDIFERENTESEPARADO_cdd702</name>
   <tag></tag>
   <elementGuidId>cae2b8ae-4ad0-493e-8533-8b2faf036ea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ESTCIVSEC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ESTCIVSEC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e4b3c8c1-eff5-476f-a936-d0b7162a0eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012ESTCIVSEC</value>
      <webElementGuid>2c353712-332a-4c44-9d46-38395fb08fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012ESTCIVSEC</value>
      <webElementGuid>e1ab5936-7200-4516-aed7-b275382cbe2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>0111aa10-d644-4a4e-9d6f-9d460e8e60fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>bb40baab-ba00-406a-83d1-91c14f5774f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 121,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>407928e5-70ca-431c-b638-5765b2218705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>ed77c1bb-68bd-4432-b95b-9b365be7c9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,121);</value>
      <webElementGuid>8d5a6476-20c6-4f74-9125-b72746f63859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>78bb03d3-d7df-4172-913c-f05d9652fe9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
...Seleccione...CASADOINDIFERENTESEPARADOSOLTEROUNIÓN LIBREVIUDO</value>
      <webElementGuid>6a067ddc-61b6-4a0b-aa13-ffb85cb558b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012ESTCIVSEC&quot;)</value>
      <webElementGuid>74d19635-9523-4980-a7f3-bb11867d735a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ESTCIVSEC']</value>
      <webElementGuid>1f0c1c37-2203-4a95-8497-911b19ab38eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[9]/div[2]/div/div/select</value>
      <webElementGuid>c45f4b54-b758-4458-ad8c-5aca9f1039a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado civil'])[1]/following::select[1]</value>
      <webElementGuid>c88a0335-9f44-4d1d-bbfb-8640c5a0f78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libreta Militar'])[1]/following::select[1]</value>
      <webElementGuid>008c8b9b-0a59-48a2-aff2-a414c79cc05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel de Escolaridad'])[1]/preceding::select[1]</value>
      <webElementGuid>547b9944-4a88-46a1-9db5-16ba7a0a9020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Población'])[1]/preceding::select[2]</value>
      <webElementGuid>f73f004d-6675-49b7-ae59-3ad059f5f952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/select</value>
      <webElementGuid>678ac4ff-ea3e-4ce7-abdf-e856c86c529d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ESTCIVSEC' and @name = 'W0026W0007W0012ESTCIVSEC' and (text() = '
...Seleccione...CASADOINDIFERENTESEPARADOSOLTEROUNIÓN LIBREVIUDO' or . = '
...Seleccione...CASADOINDIFERENTESEPARADOSOLTEROUNIÓN LIBREVIUDO')]</value>
      <webElementGuid>f3aa8c9e-2657-4c4b-b85a-dee329aa69cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
