<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.SINO_1_2_3</name>
   <tag></tag>
   <elementGuidId>4345882c-974a-4262-abbe-2540efeb8806</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='vCOMBO_0004']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vCOMBO_0004</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d56be704-18d7-42d4-bf7f-6e3b5a29ef43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vCOMBO_0004</value>
      <webElementGuid>a128745c-681f-44ca-9de6-ad000507b73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vCOMBO_0004</value>
      <webElementGuid>cb0388bd-00b3-4751-92d5-c006abff9f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn form-control</value>
      <webElementGuid>b8301066-9060-4bad-a1b9-d27868e343ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 52,'',false,'0004',24)</value>
      <webElementGuid>490f5d0c-e73a-494e-82f5-e2d3ff1a1281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>65f854a6-c717-4f7b-a1b5-add9560a8c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,52);</value>
      <webElementGuid>9c7b3ba9-a919-41ca-b449-443bca1ce53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if( !gx.evt.jsEvent(this)) return false;</value>
      <webElementGuid>af57f063-c7e2-45b2-b70a-d225759672ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione...SINO</value>
      <webElementGuid>a7375f5e-3c07-47b5-ba92-b08f862d1f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vCOMBO_0004&quot;)</value>
      <webElementGuid>8b1446ac-84e3-4549-9781-f545bee070b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Crear Candidatos/Page_Candidatos/iframe_Informacin Adicional Requerida_gxp0_ifrm</value>
      <webElementGuid>881a0f98-f7c1-4474-a259-3ae8944867e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='vCOMBO_0004']</value>
      <webElementGuid>279af19d-90fa-4cb0-b27a-043d38f6a93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TABLE_CONTAINER_TITULOFIELDCONTAINER_0004']/div[5]/select</value>
      <webElementGuid>9f74254e-ea9b-4c92-b885-a05e48ef7e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titulo'])[4]/following::select[1]</value>
      <webElementGuid>f35cb835-417c-404b-b6a6-79dccd1b6009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POBLACIÓN CAMPESINA'])[1]/following::select[1]</value>
      <webElementGuid>451a189b-c3d4-4050-a16e-7d10c73a78ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Si'])[4]/preceding::select[1]</value>
      <webElementGuid>1d41ed14-d8d6-4fcf-a648-02d093f13160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POBLACIÓN CAMPESINA'])[2]/preceding::select[1]</value>
      <webElementGuid>e1c937ab-6071-4f41-8576-6093f1e9a7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/table/tbody/tr/td/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div[5]/select</value>
      <webElementGuid>b32ebbeb-861f-4d99-a2fc-26cd247de3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'vCOMBO_0004' and @name = 'vCOMBO_0004' and (text() = 'Seleccione...SINO' or . = 'Seleccione...SINO')]</value>
      <webElementGuid>0acfc3c7-e220-4a1a-a151-ac55ecd8e9a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
