<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.ABEJORRALABRIAQUALEJANDRA_874242</name>
   <tag></tag>
   <elementGuidId>2f4d401a-4178-4fe8-83c2-0b4fecd8a5e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANRESMUNSEC</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012ECANRESMUNSEC&quot;)[count(. | //*[@id = 'W0031W0007W0012ECANRESMUNSEC' and @name = 'W0031W0007W0012ECANRESMUNSEC']) = count(//*[@id = 'W0031W0007W0012ECANRESMUNSEC' and @name = 'W0031W0007W0012ECANRESMUNSEC'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ECANRESMUNSEC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>38e01b77-0735-4a1a-8e1e-bf914a042e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANRESMUNSEC</value>
      <webElementGuid>aa585173-171e-47ef-b055-e55b0f98148d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANRESMUNSEC</value>
      <webElementGuid>85b9438d-ac6e-4550-a693-b2473ef12e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>11b34e4a-e6c3-4ffd-ae9a-6ea26704f021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>13043326-41ef-4e82-9956-519660e50e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 259,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>a33f6989-6e79-4dcd-8bbb-cb4bf75e6296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>0e28e507-5672-412f-802a-f1661ca601d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,259);</value>
      <webElementGuid>bbddf7c9-6f10-4603-86f6-06fe45d6c149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ee1c9c84-03d4-4fac-9f5f-ffd466d2a713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0a6eeec2-6b51-4d19-b00a-2e29c8fdc777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Seleccione...ABEJORRALABRIAQUÍALEJANDRÍAAMAGÁAMALFIANDESANGELÓPOLISANGOSTURAANORÍANZÁAPARTADÓARBOLETESARGELIAARMENIABARBOSABELLOBELMIRABETANIABETULIABRICEÑOBURITICÁCAICEDOCALDASCAMPAMENTOCARACOLÍCARAMANTACAREPACAROLINACAUCASIACAÑASGORDASCHIGORODÓCISNEROSCIUDAD BOLÍVARCOCORNÁCONCEPCIÓNCONCORDIACOPACABANACÁCERESDABEIBADON MATÍASEBÉJICOEL BAGREEL CARMEN DE VIBORALEL SANTUARIOENGATIVAENTRERRÍOSENVIGADOFREDONIAFRONTINOGIRALDOGIRARDOTAGRANADAGUADALUPEGUARNEGUATAPÉGÓMEZ PLATAHELICONIAHISPANIAITAGÜÍITUANGOJARDÍNJERICÓLA CEJALA ESTRELLALA PINTADALA UNIÓNLIBORINAMACEOMARINILLAMEDELLÍNMONTEBELLOMURINDÓMUTATÁNARIÑONECHÍNECOCLÍOLAYAPEQUEPEÑOLPUEBLORRICOPUERTO BERRÍOPUERTO NAREPUERTO TRIUNFOREMEDIOSRETIRORIONEGROSABANALARGASABANETASALGARSAN ANDRÉS DE CUERQUIASAN CARLOSSAN FRANCISCOSAN JERÓNIMOSAN JOSÉ DE LA MONTAÑASAN JUAN DE URABÁSAN LUISSAN PEDROSAN PEDRO DE URABÁSAN RAFAELSAN ROQUESAN VICENTESANTA BÁRBARASANTA ROSA DE OSOSSANTAFÉ DE ANTIOQUIASANTO DOMINGOSEGOVIASONSÓNSOPETRÁNTARAZÁTARSOTITIRIBÍTOLEDOTURBOTÁMESISURAMITAURRAOVALDIVIAVALPARAÍSOVEGACHÍVENECIAVIGÍA DEL FUERTEYALÍYARUMALYOLOMBÓYONDÓZARAGOZA</value>
      <webElementGuid>a453ee25-9732-4aed-84ef-db783fc927fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ECANRESMUNSEC&quot;)</value>
      <webElementGuid>4ccd3899-2497-4829-a3d2-040dd7e5fa53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ECANRESMUNSEC']</value>
      <webElementGuid>0f73efbd-8fe2-427f-ad90-cf2fe9cca844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP3TABLECONTENT']/div[3]/div/div/div/select</value>
      <webElementGuid>9a915b69-9b6e-400e-b827-ed693e6fec9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Municipio Residencia'])[1]/following::select[1]</value>
      <webElementGuid>9a3dae6a-b44e-4127-b6a1-6f5594a0ff29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento Residencia'])[1]/following::select[2]</value>
      <webElementGuid>056ce43e-cc04-4499-ae3d-2ba6d007b863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estrato'])[1]/preceding::select[1]</value>
      <webElementGuid>ea686f26-8fac-4a71-bd2d-aa57ac7ff739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teléfono'])[1]/preceding::select[2]</value>
      <webElementGuid>52584008-521d-4017-be48-35ffd7a5eb57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/fieldset/div/div[3]/div/div/div/select</value>
      <webElementGuid>b94adaed-6829-4ad5-a9b4-605b5d26e362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ECANRESMUNSEC' and @name = 'W0026W0007W0012ECANRESMUNSEC' and (text() = '
Seleccione...ABEJORRALABRIAQUÍALEJANDRÍAAMAGÁAMALFIANDESANGELÓPOLISANGOSTURAANORÍANZÁAPARTADÓARBOLETESARGELIAARMENIABARBOSABELLOBELMIRABETANIABETULIABRICEÑOBURITICÁCAICEDOCALDASCAMPAMENTOCARACOLÍCARAMANTACAREPACAROLINACAUCASIACAÑASGORDASCHIGORODÓCISNEROSCIUDAD BOLÍVARCOCORNÁCONCEPCIÓNCONCORDIACOPACABANACÁCERESDABEIBADON MATÍASEBÉJICOEL BAGREEL CARMEN DE VIBORALEL SANTUARIOENGATIVAENTRERRÍOSENVIGADOFREDONIAFRONTINOGIRALDOGIRARDOTAGRANADAGUADALUPEGUARNEGUATAPÉGÓMEZ PLATAHELICONIAHISPANIAITAGÜÍITUANGOJARDÍNJERICÓLA CEJALA ESTRELLALA PINTADALA UNIÓNLIBORINAMACEOMARINILLAMEDELLÍNMONTEBELLOMURINDÓMUTATÁNARIÑONECHÍNECOCLÍOLAYAPEQUEPEÑOLPUEBLORRICOPUERTO BERRÍOPUERTO NAREPUERTO TRIUNFOREMEDIOSRETIRORIONEGROSABANALARGASABANETASALGARSAN ANDRÉS DE CUERQUIASAN CARLOSSAN FRANCISCOSAN JERÓNIMOSAN JOSÉ DE LA MONTAÑASAN JUAN DE URABÁSAN LUISSAN PEDROSAN PEDRO DE URABÁSAN RAFAELSAN ROQUESAN VICENTESANTA BÁRBARASANTA ROSA DE OSOSSANTAFÉ DE ANTIOQUIASANTO DOMINGOSEGOVIASONSÓNSOPETRÁNTARAZÁTARSOTITIRIBÍTOLEDOTURBOTÁMESISURAMITAURRAOVALDIVIAVALPARAÍSOVEGACHÍVENECIAVIGÍA DEL FUERTEYALÍYARUMALYOLOMBÓYONDÓZARAGOZA' or . = '
Seleccione...ABEJORRALABRIAQUÍALEJANDRÍAAMAGÁAMALFIANDESANGELÓPOLISANGOSTURAANORÍANZÁAPARTADÓARBOLETESARGELIAARMENIABARBOSABELLOBELMIRABETANIABETULIABRICEÑOBURITICÁCAICEDOCALDASCAMPAMENTOCARACOLÍCARAMANTACAREPACAROLINACAUCASIACAÑASGORDASCHIGORODÓCISNEROSCIUDAD BOLÍVARCOCORNÁCONCEPCIÓNCONCORDIACOPACABANACÁCERESDABEIBADON MATÍASEBÉJICOEL BAGREEL CARMEN DE VIBORALEL SANTUARIOENGATIVAENTRERRÍOSENVIGADOFREDONIAFRONTINOGIRALDOGIRARDOTAGRANADAGUADALUPEGUARNEGUATAPÉGÓMEZ PLATAHELICONIAHISPANIAITAGÜÍITUANGOJARDÍNJERICÓLA CEJALA ESTRELLALA PINTADALA UNIÓNLIBORINAMACEOMARINILLAMEDELLÍNMONTEBELLOMURINDÓMUTATÁNARIÑONECHÍNECOCLÍOLAYAPEQUEPEÑOLPUEBLORRICOPUERTO BERRÍOPUERTO NAREPUERTO TRIUNFOREMEDIOSRETIRORIONEGROSABANALARGASABANETASALGARSAN ANDRÉS DE CUERQUIASAN CARLOSSAN FRANCISCOSAN JERÓNIMOSAN JOSÉ DE LA MONTAÑASAN JUAN DE URABÁSAN LUISSAN PEDROSAN PEDRO DE URABÁSAN RAFAELSAN ROQUESAN VICENTESANTA BÁRBARASANTA ROSA DE OSOSSANTAFÉ DE ANTIOQUIASANTO DOMINGOSEGOVIASONSÓNSOPETRÁNTARAZÁTARSOTITIRIBÍTOLEDOTURBOTÁMESISURAMITAURRAOVALDIVIAVALPARAÍSOVEGACHÍVENECIAVIGÍA DEL FUERTEYALÍYARUMALYOLOMBÓYONDÓZARAGOZA')]</value>
      <webElementGuid>1d0d9e66-c6de-4d01-83fc-749aae232216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
