<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.AMAZONASANTIOQUIAARAUCAAT_c008ef</name>
   <tag></tag>
   <elementGuidId>b57d1b75-b5b7-4080-9045-fb5881e45a90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012vDEPSECEXP</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012vDEPSECEXP&quot;)[count(. | //*[@id = 'W0031W0007W0012vDEPSECEXP' and @name = 'W0031W0007W0012vDEPSECEXP']) = count(//*[@id = 'W0031W0007W0012vDEPSECEXP' and @name = 'W0031W0007W0012vDEPSECEXP'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012vDEPSECEXP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ebae664b-a9f8-439b-a010-d88de11e493b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012vDEPSECEXP</value>
      <webElementGuid>b85e2ed2-1599-4c9a-a475-bf04bcd59e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012vDEPSECEXP</value>
      <webElementGuid>d1d7f126-0e8f-4853-98af-0ba75a9107b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>a1c9f622-a68c-439d-a8ef-e19534617541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>ce2ad3de-f555-4385-8ce6-c79ebe36aa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 85,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>c166227a-2796-4053-9629-29304b40795a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>a94bf8fd-c976-4819-bc7e-b454093fbb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,85);</value>
      <webElementGuid>8b87a2c7-4bbe-46f1-9d9a-63de9732f6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a0a6d900-c15b-42ae-b420-bb4682826cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8ad78b52-8bac-4e3e-b3ab-646d61a29bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Seleccione...AMAZONASANTIOQUIAARAUCAATLÁNTICOBOGOTÁBOLÍVARBOYACÁCALDASCAQUETÁCASANARECAUCACESARCHOCÓCUNDINAMARCACÓRDOBAGUAINÍAGUAVIAREHUILALA GUAJIRAMAGDALENAMETANARIÑONORTE DE SANTANDERPUTUMAYOQUINDÍORISARALDASAN ANDRES Y PROVIDENCIASANTANDERSUCRETOLIMAVALLE DEL CAUCAVAUPÉSVICHADA</value>
      <webElementGuid>d759f731-4b78-44e7-b2f2-4e180ef8906d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012vDEPSECEXP&quot;)</value>
      <webElementGuid>d24aba78-265e-4b13-a34e-e0356b7951b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012vDEPSECEXP']</value>
      <webElementGuid>a21c1726-8302-40b4-91b0-d527d34885ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[5]/div[2]/div/div/select</value>
      <webElementGuid>0047ff1f-7ab4-4374-b28e-41357d5fa964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento Expedición'])[1]/following::select[1]</value>
      <webElementGuid>3a3fd052-0c0b-43bd-9896-5bae7ad44c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País Expedición'])[1]/following::select[2]</value>
      <webElementGuid>e8417a9f-b55b-4ff3-90fd-e51577da8884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciudad Expedición'])[1]/preceding::select[1]</value>
      <webElementGuid>57142e90-1de2-49f5-833c-13bda3a797bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Expedición*'])[1]/preceding::select[2]</value>
      <webElementGuid>2a9de724-bcc9-4afe-b4ed-9069b2cc4211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/select</value>
      <webElementGuid>1c7dd7c2-ebfa-42cf-bf6d-bc8d7ee623f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012vDEPSECEXP' and @name = 'W0026W0007W0012vDEPSECEXP' and (text() = '
Seleccione...AMAZONASANTIOQUIAARAUCAATLÁNTICOBOGOTÁBOLÍVARBOYACÁCALDASCAQUETÁCASANARECAUCACESARCHOCÓCUNDINAMARCACÓRDOBAGUAINÍAGUAVIAREHUILALA GUAJIRAMAGDALENAMETANARIÑONORTE DE SANTANDERPUTUMAYOQUINDÍORISARALDASAN ANDRES Y PROVIDENCIASANTANDERSUCRETOLIMAVALLE DEL CAUCAVAUPÉSVICHADA' or . = '
Seleccione...AMAZONASANTIOQUIAARAUCAATLÁNTICOBOGOTÁBOLÍVARBOYACÁCALDASCAQUETÁCASANARECAUCACESARCHOCÓCUNDINAMARCACÓRDOBAGUAINÍAGUAVIAREHUILALA GUAJIRAMAGDALENAMETANARIÑONORTE DE SANTANDERPUTUMAYOQUINDÍORISARALDASAN ANDRES Y PROVIDENCIASANTANDERSUCRETOLIMAVALLE DEL CAUCAVAUPÉSVICHADA')]</value>
      <webElementGuid>1c5e8f1d-dbef-45e3-8834-56f0a8eede62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
