<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.ARAUCAARAUQUITACRAVO NORT_4b0dac</name>
   <tag></tag>
   <elementGuidId>6041d1a1-f75b-4788-a7f5-89a616552426</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ECANNACMUNSEC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANNACMUNSEC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f7a0a1dc-e5f0-4772-920b-e9c42789f1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012ECANNACMUNSEC</value>
      <webElementGuid>900cddb8-047e-4c84-98bd-ec7be3475897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012ECANNACMUNSEC</value>
      <webElementGuid>8b96e21f-901a-49e1-b48c-36a49c85e622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>7226e2ba-7b8b-4eab-a3eb-5bc341880fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>cab0ba97-0fb3-4ad0-aee6-f40775225d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 108,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>6e867196-3484-4a69-866f-9df0eaec6207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>8de73331-a46a-4edd-9c71-4a45f12305de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,108);</value>
      <webElementGuid>3db9caf9-916a-417a-8c89-c4874ea1c4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bc44b159-b7b7-4e63-989d-93fd14436606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f67089d2-5076-4a3f-ae19-a76bd23b4631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Seleccione...ARAUCAARAUQUITACRAVO NORTEFORTULPUERTO RONDÓNSARAVENATAME</value>
      <webElementGuid>aac68454-8f24-4a0f-812a-47da8e0f6e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012ECANNACMUNSEC&quot;)</value>
      <webElementGuid>e5715c2e-dcce-403d-bc67-36312ba757cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ECANNACMUNSEC']</value>
      <webElementGuid>8430fe6e-5e7e-4ef9-97dc-7d0d31e846f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[8]/div/div/div/select</value>
      <webElementGuid>85601fdd-6016-420a-aa47-4e50670331ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Municipio Nacimiento'])[1]/following::select[1]</value>
      <webElementGuid>3557fff3-03e5-47f1-834d-76039d01f38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento Nacimiento'])[1]/following::select[2]</value>
      <webElementGuid>6a39eb14-0240-4ffd-8f88-4976695c4ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comunidad LGBTI'])[1]/preceding::select[1]</value>
      <webElementGuid>030aa617-af6d-4d09-aadc-d881ba72e6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libreta Militar'])[1]/preceding::select[2]</value>
      <webElementGuid>d17b3d6b-f053-48a7-a61e-2f6d5618dcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/select</value>
      <webElementGuid>28683cb0-ed88-475b-9fcd-aba89f8ac303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ECANNACMUNSEC' and @name = 'W0026W0007W0012ECANNACMUNSEC' and (text() = '
Seleccione...ARAUCAARAUQUITACRAVO NORTEFORTULPUERTO RONDÓNSARAVENATAME' or . = '
Seleccione...ARAUCAARAUQUITACRAVO NORTEFORTULPUERTO RONDÓNSARAVENATAME')]</value>
      <webElementGuid>e3273106-e89b-43b8-816b-a64d39fe17ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
