<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.TRESCUATROCINCOUNODOSSEIS</name>
   <tag></tag>
   <elementGuidId>286ccc62-c546-486a-8cdd-f194cf851bbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ESTSEC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ESTSEC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7b14f68c-4b19-40aa-82e1-21b11b047d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012ESTSEC</value>
      <webElementGuid>f2aa2dd5-81e8-457f-87ba-85911fcccadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012ESTSEC</value>
      <webElementGuid>966684b3-a20f-4a3f-a88f-017a16771f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>3fd97d59-3896-48bb-814b-948643271b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>0afee226-9cd5-486f-9b95-f29879cf9f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 263,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>cd4fed6c-5302-4725-bc8b-5db75b65d582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>362a8b6f-bd8d-44d3-9dd2-acd62de4d860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,263);</value>
      <webElementGuid>d1d3c717-7a62-47b1-b70c-d132aca902ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4ee394d3-5eab-4414-a3c5-c140c95d24b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
...Seleccione...TRESCUATROCINCOUNODOSSEIS</value>
      <webElementGuid>172bc79c-6cb6-4b28-9744-203053aa9110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012ESTSEC&quot;)</value>
      <webElementGuid>9f7d3c68-a7da-4754-8198-d00826ca39b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ESTSEC']</value>
      <webElementGuid>004a1465-e207-4066-b4a7-c9cb3c4d5b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP3TABLECONTENT']/div[3]/div[2]/div/div/select</value>
      <webElementGuid>e71a8a71-863b-4111-9cea-6186f0ea43c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estrato'])[1]/following::select[1]</value>
      <webElementGuid>f456a90d-ba8d-4b3d-92a6-73b4715d87e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Municipio Residencia'])[1]/following::select[2]</value>
      <webElementGuid>7307e080-0aab-459f-9a3f-9c82eab25e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teléfono'])[1]/preceding::select[1]</value>
      <webElementGuid>7706c9aa-5fb0-4e8d-87ef-afd13c10a2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Celular'])[1]/preceding::select[1]</value>
      <webElementGuid>671f1fa9-335a-4edd-82c2-8019d35225e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/select</value>
      <webElementGuid>e816cc83-6f8d-489d-93c5-dffc8af7affa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ESTSEC' and @name = 'W0026W0007W0012ESTSEC' and (text() = '
...Seleccione...TRESCUATROCINCOUNODOSSEIS' or . = '
...Seleccione...TRESCUATROCINCOUNODOSSEIS')]</value>
      <webElementGuid>48af09e3-6937-45a0-aa3d-19e825576e5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
