<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.ABANDONO O DESPOJO FORZAD_e1afd4</name>
   <tag></tag>
   <elementGuidId>faef376f-26d5-44ad-aa50-01d75899c525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ETIPPOBSEC</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'W0031W0007W0012ETIPPOBSEC' and @name = 'W0031W0007W0012ETIPPOBSEC']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ETIPPOBSEC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c75116ab-6734-4bb3-b6fc-941eef0fd792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ETIPPOBSEC</value>
      <webElementGuid>56726a75-bf3e-4a28-aae0-a9212085ba43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ETIPPOBSEC</value>
      <webElementGuid>ab39baf9-6a65-43fe-bd1b-39a5b7890d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>ba5fe8c8-168d-40ed-b9e1-6b64d1ddb5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>2c941f26-574a-45ef-b968-c94b35751179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 130,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>4035ceb6-9930-4cb8-9e03-4df6d02fae16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>1213b36d-a5c7-4f48-8bfb-c1b3dcf3bfcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,130);</value>
      <webElementGuid>06f0d5f3-e417-4b50-be7b-189910233082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e95e9cbe-e16d-4a5d-b626-d040d28b5464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
...Seleccione...ABANDONO O DESPOJO FORZADO DE TIERRASACTOS TERRORISTAS/ATENTADOS/COMBATES/ENFRENTAMIENTOSADOLESCENTE DESVINCULADO DE GRUPOS ARMADOSADOLESCENTE EN CONFLICTO CON LA LEY PENALADOLESCENTE TRABAJADORAFROCOLOMBIANOSAFROCOLOMBIANOS DESPLAZADOS POR LA VIOLENCIAAFROCOLOMBIANOS DESPLAZADOS POR LA VIOLENCIA CABEZA DEAMENAZAARTESANOSCOMUNIDAD RROMMDELITOS CONTRA LA LIBERTAD Y LA INTEGRIDAD SEXUAL EN DESARROLLO DELDESAPARICIÓN FORZADADESPLAZADOS DISCAPACITADOSDESPLAZADOS POR FENOMENOS NATURALESDESPLAZADOS POR FENÓMENOS NATURALES CABEZA DE FAMILIADESPLAZADOS POR LA VIOLENCIADESPLAZADOS POR LA VIOLENCIA CABEZA DE FAMILIAEMPRENDEDORESHERIDOHOMICIDIO/MASACREINDIGENASINDIGENAS DESPLAZADOS POR LA VIOLENCIAINDIGENAS DESPLAZADOS POR LA VIOLENCIA DE FAMILIAINPECJÓVENES VULNERABLESMICROEMPRESASMINAS ANTIPERSONAL, MUNICIÓN SIN EXPLOTAR, ARTEFACTO EXPLOSIVOMUJER CABEZA DE FAMILIANEGRITUDESNINGUNAPALENQUEROSPERSONAS EN PROCESO DE REINTEGRACIÓNRAIZALESRECLUTAMIENTO FORZADOREMITIDOS POR EL CIEREMITIDOS POR EL PALSECUESTROSOLDADOS CAMPESINOSTERCERA EDADTORTURAVINCULACIÓN DE NIÑOS,NIÑAS Y ADOLESCENTES A ACTIVIDADES RELACIONADA</value>
      <webElementGuid>a14e485b-42b0-4ef4-9dba-3485d8fd1c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ETIPPOBSEC&quot;)</value>
      <webElementGuid>1cde89ea-733e-4931-819b-f8e844c4fc78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ETIPPOBSEC']</value>
      <webElementGuid>99413c77-6f58-4927-9eea-f71a2b60e54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[10]/div[2]/div/div/select</value>
      <webElementGuid>2cdae976-8fd2-45b6-9f5a-5f04146f7582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Población'])[1]/following::select[1]</value>
      <webElementGuid>9aa74690-c566-4411-abf1-7cee5a9e3612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel de Escolaridad'])[1]/following::select[2]</value>
      <webElementGuid>25916a03-60f2-43f2-87e1-770baa491849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condición de discapacidad'])[1]/preceding::select[1]</value>
      <webElementGuid>7c47b3ed-18a2-402b-91ea-00041c922bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condición de discapacidad'])[2]/preceding::select[1]</value>
      <webElementGuid>94e6ad3f-47a1-47a5-aa1f-07c41bdb9646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/div/select</value>
      <webElementGuid>60fe85d9-014b-47b4-9bc7-107d15a9be55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ETIPPOBSEC' and @name = 'W0026W0007W0012ETIPPOBSEC' and (text() = '
...Seleccione...ABANDONO O DESPOJO FORZADO DE TIERRASACTOS TERRORISTAS/ATENTADOS/COMBATES/ENFRENTAMIENTOSADOLESCENTE DESVINCULADO DE GRUPOS ARMADOSADOLESCENTE EN CONFLICTO CON LA LEY PENALADOLESCENTE TRABAJADORAFROCOLOMBIANOSAFROCOLOMBIANOS DESPLAZADOS POR LA VIOLENCIAAFROCOLOMBIANOS DESPLAZADOS POR LA VIOLENCIA CABEZA DEAMENAZAARTESANOSCOMUNIDAD RROMMDELITOS CONTRA LA LIBERTAD Y LA INTEGRIDAD SEXUAL EN DESARROLLO DELDESAPARICIÓN FORZADADESPLAZADOS DISCAPACITADOSDESPLAZADOS POR FENOMENOS NATURALESDESPLAZADOS POR FENÓMENOS NATURALES CABEZA DE FAMILIADESPLAZADOS POR LA VIOLENCIADESPLAZADOS POR LA VIOLENCIA CABEZA DE FAMILIAEMPRENDEDORESHERIDOHOMICIDIO/MASACREINDIGENASINDIGENAS DESPLAZADOS POR LA VIOLENCIAINDIGENAS DESPLAZADOS POR LA VIOLENCIA DE FAMILIAINPECJÓVENES VULNERABLESMICROEMPRESASMINAS ANTIPERSONAL, MUNICIÓN SIN EXPLOTAR, ARTEFACTO EXPLOSIVOMUJER CABEZA DE FAMILIANEGRITUDESNINGUNAPALENQUEROSPERSONAS EN PROCESO DE REINTEGRACIÓNRAIZALESRECLUTAMIENTO FORZADOREMITIDOS POR EL CIEREMITIDOS POR EL PALSECUESTROSOLDADOS CAMPESINOSTERCERA EDADTORTURAVINCULACIÓN DE NIÑOS,NIÑAS Y ADOLESCENTES A ACTIVIDADES RELACIONADA' or . = '
...Seleccione...ABANDONO O DESPOJO FORZADO DE TIERRASACTOS TERRORISTAS/ATENTADOS/COMBATES/ENFRENTAMIENTOSADOLESCENTE DESVINCULADO DE GRUPOS ARMADOSADOLESCENTE EN CONFLICTO CON LA LEY PENALADOLESCENTE TRABAJADORAFROCOLOMBIANOSAFROCOLOMBIANOS DESPLAZADOS POR LA VIOLENCIAAFROCOLOMBIANOS DESPLAZADOS POR LA VIOLENCIA CABEZA DEAMENAZAARTESANOSCOMUNIDAD RROMMDELITOS CONTRA LA LIBERTAD Y LA INTEGRIDAD SEXUAL EN DESARROLLO DELDESAPARICIÓN FORZADADESPLAZADOS DISCAPACITADOSDESPLAZADOS POR FENOMENOS NATURALESDESPLAZADOS POR FENÓMENOS NATURALES CABEZA DE FAMILIADESPLAZADOS POR LA VIOLENCIADESPLAZADOS POR LA VIOLENCIA CABEZA DE FAMILIAEMPRENDEDORESHERIDOHOMICIDIO/MASACREINDIGENASINDIGENAS DESPLAZADOS POR LA VIOLENCIAINDIGENAS DESPLAZADOS POR LA VIOLENCIA DE FAMILIAINPECJÓVENES VULNERABLESMICROEMPRESASMINAS ANTIPERSONAL, MUNICIÓN SIN EXPLOTAR, ARTEFACTO EXPLOSIVOMUJER CABEZA DE FAMILIANEGRITUDESNINGUNAPALENQUEROSPERSONAS EN PROCESO DE REINTEGRACIÓNRAIZALESRECLUTAMIENTO FORZADOREMITIDOS POR EL CIEREMITIDOS POR EL PALSECUESTROSOLDADOS CAMPESINOSTERCERA EDADTORTURAVINCULACIÓN DE NIÑOS,NIÑAS Y ADOLESCENTES A ACTIVIDADES RELACIONADA')]</value>
      <webElementGuid>6d59380b-aaf4-4080-9a5c-8dfe165a7886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
