<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.ARAUCAARAUQUITACRAVO NORT_4b0dac</name>
   <tag></tag>
   <elementGuidId>6041d1a1-f75b-4788-a7f5-89a616552426</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANNACMUNSEC</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012ECANNACMUNSEC&quot;)[count(. | //*[@id = 'W0031W0007W0012ECANNACMUNSEC' and @name = 'W0031W0007W0012ECANNACMUNSEC']) = count(//*[@id = 'W0031W0007W0012ECANNACMUNSEC' and @name = 'W0031W0007W0012ECANNACMUNSEC'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0031W0007W0012ECANNACMUNSEC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a328e78d-68b8-4ce6-8604-7886a34ec1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANNACMUNSEC</value>
      <webElementGuid>4be3b44b-340e-4184-b37d-e96cd1e75d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANNACMUNSEC</value>
      <webElementGuid>76f9395e-dd10-458f-8210-3cd100e802b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>611dd451-cd57-4743-838a-20307c8ff355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>0195de0c-d3e1-498d-9454-ae0f2ce4096a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 108,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>bb73f830-17d8-41a0-9a96-404d857f06d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>e0b2cb7a-add2-4c1c-b616-11bb8b35edf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,108);</value>
      <webElementGuid>5c9fbe0d-e459-48b1-9168-27e4d161d95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b384094c-2cea-46dc-a1ac-eb0211fee7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ada56c49-5500-4ca8-9be9-88cda1df3276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Seleccione...ARAUCAARAUQUITACRAVO NORTEFORTULPUERTO RONDÓNSARAVENATAME</value>
      <webElementGuid>69790f0c-4754-48d0-af2f-bccb3bfc0092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ECANNACMUNSEC&quot;)</value>
      <webElementGuid>1954837d-7899-446c-9839-8deaeaa78a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0031W0007W0012ECANNACMUNSEC']</value>
      <webElementGuid>efcb9a74-3e3e-4f01-9ee7-e5735ec3a9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0031W0007W0012GROUP0TABLECONTENT']/div[8]/div/div/div/select</value>
      <webElementGuid>3bc408ab-29f5-4ff0-8b84-351b1f999b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Municipio Nacimiento'])[1]/following::select[1]</value>
      <webElementGuid>0798dfa1-df93-48a0-997b-c58157e74993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento Nacimiento'])[1]/following::select[2]</value>
      <webElementGuid>89545a25-b019-43f6-9686-44385a2bdab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comunidad LGBTI'])[1]/preceding::select[1]</value>
      <webElementGuid>31fdfe28-3ef3-41b7-9faf-591e2656b774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libreta Militar'])[1]/preceding::select[2]</value>
      <webElementGuid>dbd84b42-9d39-4bb9-b1e9-4bc8b9485033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/select</value>
      <webElementGuid>1ae1177b-f0b8-4204-b72c-dde81ddf0609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0031W0007W0012ECANNACMUNSEC' and @name = 'W0026W0007W0012ECANNACMUNSEC' and (text() = '
Seleccione...ARAUCAARAUQUITACRAVO NORTEFORTULPUERTO RONDÓNSARAVENATAME' or . = '
Seleccione...ARAUCAARAUQUITACRAVO NORTEFORTULPUERTO RONDÓNSARAVENATAME')]</value>
      <webElementGuid>9fb8bd24-d01a-434e-aaa7-ba60e688b202</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
