<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.NINGUNOPRIMARIAMEDIABACHI_b4fc22</name>
   <tag></tag>
   <elementGuidId>3bf49e8b-d5be-46cb-afc3-fe1351bb3626</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ENIVESCSEC</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012ENIVESCSEC&quot;)[count(. | //*[@id = 'W0031W0007W0012ENIVESCSEC' and @name = 'W0031W0007W0012ENIVESCSEC']) = count(//*[@id = 'W0031W0007W0012ENIVESCSEC' and @name = 'W0031W0007W0012ENIVESCSEC'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ENIVESCSEC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7edd5af6-8717-42ba-85ed-88ed2c07390d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ENIVESCSEC</value>
      <webElementGuid>c671ad26-fc0e-4b53-b914-d68cac032fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ENIVESCSEC</value>
      <webElementGuid>76bf7330-19f4-4b12-8885-85d4bbf67593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>78ad391d-75be-48a3-bb47-0eb7c09e1ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>7b5773cc-639b-40bf-9ed7-b2621a256af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 126,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>cdf48bad-a139-4032-8640-175305eaeade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>806290b2-d0cf-482a-a42e-3ddc69e551d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,126);</value>
      <webElementGuid>1c2a3165-2c8b-4e0e-abae-4b4a6f5d7910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e9340ec0-1dcd-403a-892c-c6730eb3b4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
...Seleccione...NINGUNOPRIMARIAMEDIABACHILLERTÉCNICOTECNÓLOGOPROFESIONALESPECIALIZACIÓNMAESTRÍADOCTORADO</value>
      <webElementGuid>08325466-6991-4913-a6ca-fd91715decb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ENIVESCSEC&quot;)</value>
      <webElementGuid>0fc7756a-bdfa-4309-858d-c08eda25c3f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ENIVESCSEC']</value>
      <webElementGuid>3ee184d4-2026-4434-82fb-be5b2edfdfb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[10]/div/div/div/select</value>
      <webElementGuid>4f2998c2-3b30-430b-993a-97c118611e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel de Escolaridad'])[1]/following::select[1]</value>
      <webElementGuid>b432366e-2920-414d-a6a8-7ee7cf1682e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado civil'])[1]/following::select[2]</value>
      <webElementGuid>cb04426f-0171-405f-a142-02b3b54e09ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Población'])[1]/preceding::select[1]</value>
      <webElementGuid>2b6036a1-6eec-4c2d-869f-8c29a620f14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condición de discapacidad'])[1]/preceding::select[2]</value>
      <webElementGuid>84c4e7d7-b282-4439-ab2c-210b40ffcb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/select</value>
      <webElementGuid>1088c77e-03d0-4002-831a-a6cd2d530023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ENIVESCSEC' and @name = 'W0026W0007W0012ENIVESCSEC' and (text() = '
...Seleccione...NINGUNOPRIMARIAMEDIABACHILLERTÉCNICOTECNÓLOGOPROFESIONALESPECIALIZACIÓNMAESTRÍADOCTORADO' or . = '
...Seleccione...NINGUNOPRIMARIAMEDIABACHILLERTÉCNICOTECNÓLOGOPROFESIONALESPECIALIZACIÓNMAESTRÍADOCTORADO')]</value>
      <webElementGuid>df5c7b52-4f89-47f9-84ce-b45b175dbbeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
