<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.SINO_InfAdCan 3</name>
   <tag></tag>
   <elementGuidId>10aa243b-dd8c-45c1-9a32-2884a3c5f93d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0031W0007W0012W0239vCOMBO_0002</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0031W0007W0012W0243vCOMBO_0003']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012W0239vCOMBO_0003&quot;)[count(. | //*[@id = 'W0031W0007W0012W0239vCOMBO_0003' and @name = 'W0031W0007W0012W0239vCOMBO_0003' and (text() = 'Seleccione...SINO' or . = 'Seleccione...SINO')]) = count(//*[@id = 'W0031W0007W0012W0239vCOMBO_0003' and @name = 'W0031W0007W0012W0239vCOMBO_0003' and (text() = 'Seleccione...SINO' or . = 'Seleccione...SINO')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f8add10b-953c-4fa4-91a2-f0d0ae69909c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012W0239vCOMBO_0003</value>
      <webElementGuid>cb3ea321-1b96-4cbf-99cc-9a1e1305cba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012W0239vCOMBO_0003</value>
      <webElementGuid>a2a15c1f-ca39-4a16-9909-7b1dd97ae5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn form-control</value>
      <webElementGuid>5f8eb8a1-fced-4ea0-81bc-2a4f5b9cce74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 49,'W0031W0007W0012W0239',false,'0002',21)</value>
      <webElementGuid>8a711225-6aa1-40ef-87c0-06cc4c0f0387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>cb0de514-2aef-40c3-b937-9b66464dcb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,49);</value>
      <webElementGuid>505f2a23-06b1-47fb-a5c2-fcc27f17cb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if( !gx.evt.jsEvent(this)) return false;</value>
      <webElementGuid>7dd3f09b-2256-49a5-9fb7-225698da3982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione...SINO</value>
      <webElementGuid>49f93c30-86ec-4413-92fb-2f918cfd5f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012W0239vCOMBO_0003&quot;)</value>
      <webElementGuid>8830c02d-39aa-4c4d-bc62-9aa23077a1d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0031W0007W0012W0239vCOMBO_0002']</value>
      <webElementGuid>a02f2cdd-a243-4c2e-b922-efe55ff7559a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0031W0007W0012W0239TABLE_CONTAINER_TITULOFIELDCONTAINER_0002']/div[5]/select</value>
      <webElementGuid>73957834-0386-48e0-bce9-5d73b7a5fec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titulo'])[2]/following::select[1]</value>
      <webElementGuid>cccd34d3-d1fb-400f-ae94-136a91aa5fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POBLACIÓN DE ACOGIDA'])[1]/following::select[1]</value>
      <webElementGuid>9bba619d-4467-4067-bb26-de86558aa82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Si'])[6]/preceding::select[1]</value>
      <webElementGuid>662dd048-15ae-4183-abbd-9fe13b331e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combo'])[2]/preceding::select[1]</value>
      <webElementGuid>a19fde62-142e-47d1-b19c-bd125974597a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div[5]/select</value>
      <webElementGuid>e5263de7-2278-4df3-a355-ce70ccd48056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0031W0007W0012W0239vCOMBO_0002' and @name = 'W0031W0007W0012W0239vCOMBO_0002' and (text() = 'Seleccione...SINO' or . = 'Seleccione...SINO')]</value>
      <webElementGuid>ed1de204-b217-48c7-9a91-e7c2fde8052b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
