<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.AGUADAALBANIAARATOCABARBO_f6a42f</name>
   <tag></tag>
   <elementGuidId>04b897ac-1f5b-46bf-8716-5f71e94c7392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANEXPMUNSEC</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012ECANEXPMUNSEC&quot;)[count(. | //*[@id = 'W0031W0007W0012ECANEXPMUNSEC' and @name = 'W0031W0007W0012ECANEXPMUNSEC']) = count(//*[@id = 'W0031W0007W0012ECANEXPMUNSEC' and @name = 'W0031W0007W0012ECANEXPMUNSEC'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ECANEXPMUNSEC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e65542ea-5afb-4397-ad1f-f7dadeb94ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANEXPMUNSEC</value>
      <webElementGuid>f02428cc-00cb-4f75-903d-232222eff475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANEXPMUNSEC</value>
      <webElementGuid>560c47a2-eddb-4531-a01e-0dc76073424b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>56978df8-b598-4111-a383-eac05849607e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>fa642c59-fa73-4b41-aa57-97fc4630b61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 90,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>fd4e066c-bcb9-4c36-9317-a33caf81d376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>d25ead7e-0984-444b-9197-5d3ae6e5551d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,90);</value>
      <webElementGuid>791445b1-82df-4979-bc66-580eb96e2d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ac39fea5-30b4-4c40-b2a7-d14497d2c07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>87d779a6-72b4-42d0-bf61-7b323973719d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Seleccione...AGUADAALBANIAARATOCABARBOSABARICHARABARRANCABERMEJABETULIABOLÍVARBUCARAMANGACABRERACALIFORNIACAPITANEJOCARCASÍCEPITÁCERRITOCHARALÁCHARTACHIMACHIPATÁCIMITARRACONCEPCIÓNCONFINESCONTRATACIÓNCOROMOROCURITÍEL CARMEN DE CHUCURÍEL GUACAMAYOEL PEÑÓNEL PLAYÓNENCINOENCISOFLORIDABLANCAFLORIÁNGALÁNGIRÓNGUACAGUADALUPEGUAPOTÁGUAVATÁGÁMBITAGÜEPSAHATOJESÚS MARÍAJORDÁNLA BELLEZALA PAZLANDAZURILEBRIJALOS SANTOSMACARAVITAMATANZAMOGOTESMOLAGAVITAMÁLAGAOCAMONTEOIBAONZAGAPALMARPALMAS DEL SOCORROPIEDECUESTAPINCHOTEPUENTE NACIONALPUERTO PARRAPUERTO WILCHESPÁRAMORIONEGROSABANA DE TORRESSAN ANDRÉSSAN BENITOSAN GILSAN JOAQUÍNSAN JOSÉ DE MIRANDASAN MIGUELSAN VICENTE DE CHUCURÍSANTA BÁRBARASANTA HELENA DEL OPÓNSIMACOTASOCORROSUAITASUCRESURATÁTONAVALLE DE SAN JOSÉVETASVILLANUEVAVÉLEZZAPATOCA</value>
      <webElementGuid>25136fe8-8708-47f9-b039-d00d02f9d764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ECANEXPMUNSEC&quot;)</value>
      <webElementGuid>599c1640-f997-4c90-b9b3-4ab33a408ebd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ECANEXPMUNSEC']</value>
      <webElementGuid>cbc393ba-5d25-4237-9e43-ccc427e2f29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[6]/div/div/div/select</value>
      <webElementGuid>14d78552-13d6-495c-98a1-f7e52c56c6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciudad Expedición'])[1]/following::select[1]</value>
      <webElementGuid>9f6ce967-c9bf-4487-8c31-4475fad5f420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento Expedición'])[1]/following::select[2]</value>
      <webElementGuid>ea62db23-a3f8-4b2c-a43f-0a28392f18ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Expedición*'])[1]/preceding::select[1]</value>
      <webElementGuid>3013278a-8640-4835-b091-865d6d2e7512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País Nacimiento'])[1]/preceding::select[1]</value>
      <webElementGuid>acc61d9c-f4c6-40fc-bb05-e1f534f88845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/select</value>
      <webElementGuid>c7f2b315-c821-4e54-b2bc-f8c949a7935f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ECANEXPMUNSEC' and @name = 'W0026W0007W0012ECANEXPMUNSEC' and (text() = '
Seleccione...AGUADAALBANIAARATOCABARBOSABARICHARABARRANCABERMEJABETULIABOLÍVARBUCARAMANGACABRERACALIFORNIACAPITANEJOCARCASÍCEPITÁCERRITOCHARALÁCHARTACHIMACHIPATÁCIMITARRACONCEPCIÓNCONFINESCONTRATACIÓNCOROMOROCURITÍEL CARMEN DE CHUCURÍEL GUACAMAYOEL PEÑÓNEL PLAYÓNENCINOENCISOFLORIDABLANCAFLORIÁNGALÁNGIRÓNGUACAGUADALUPEGUAPOTÁGUAVATÁGÁMBITAGÜEPSAHATOJESÚS MARÍAJORDÁNLA BELLEZALA PAZLANDAZURILEBRIJALOS SANTOSMACARAVITAMATANZAMOGOTESMOLAGAVITAMÁLAGAOCAMONTEOIBAONZAGAPALMARPALMAS DEL SOCORROPIEDECUESTAPINCHOTEPUENTE NACIONALPUERTO PARRAPUERTO WILCHESPÁRAMORIONEGROSABANA DE TORRESSAN ANDRÉSSAN BENITOSAN GILSAN JOAQUÍNSAN JOSÉ DE MIRANDASAN MIGUELSAN VICENTE DE CHUCURÍSANTA BÁRBARASANTA HELENA DEL OPÓNSIMACOTASOCORROSUAITASUCRESURATÁTONAVALLE DE SAN JOSÉVETASVILLANUEVAVÉLEZZAPATOCA' or . = '
Seleccione...AGUADAALBANIAARATOCABARBOSABARICHARABARRANCABERMEJABETULIABOLÍVARBUCARAMANGACABRERACALIFORNIACAPITANEJOCARCASÍCEPITÁCERRITOCHARALÁCHARTACHIMACHIPATÁCIMITARRACONCEPCIÓNCONFINESCONTRATACIÓNCOROMOROCURITÍEL CARMEN DE CHUCURÍEL GUACAMAYOEL PEÑÓNEL PLAYÓNENCINOENCISOFLORIDABLANCAFLORIÁNGALÁNGIRÓNGUACAGUADALUPEGUAPOTÁGUAVATÁGÁMBITAGÜEPSAHATOJESÚS MARÍAJORDÁNLA BELLEZALA PAZLANDAZURILEBRIJALOS SANTOSMACARAVITAMATANZAMOGOTESMOLAGAVITAMÁLAGAOCAMONTEOIBAONZAGAPALMARPALMAS DEL SOCORROPIEDECUESTAPINCHOTEPUENTE NACIONALPUERTO PARRAPUERTO WILCHESPÁRAMORIONEGROSABANA DE TORRESSAN ANDRÉSSAN BENITOSAN GILSAN JOAQUÍNSAN JOSÉ DE MIRANDASAN MIGUELSAN VICENTE DE CHUCURÍSANTA BÁRBARASANTA HELENA DEL OPÓNSIMACOTASOCORROSUAITASUCRESURATÁTONAVALLE DE SAN JOSÉVETASVILLANUEVAVÉLEZZAPATOCA')]</value>
      <webElementGuid>8706df26-1055-4c9d-8bef-23582a5b4b14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
