<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.SINO (1)</name>
   <tag></tag>
   <elementGuidId>1b177f4e-f564-4e17-b1d5-a27e84ec1178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='vCOMBO_0001']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vCOMBO_0001</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ac78c791-9a8b-411b-af3b-cb8ad937ca7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vCOMBO_0001</value>
      <webElementGuid>df498175-4086-448a-b829-715d7d1f81f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vCOMBO_0001</value>
      <webElementGuid>3fb0cae8-77e9-445a-92f1-408d9fd09ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn form-control</value>
      <webElementGuid>d28a5fb5-b6ad-4d95-a620-7f2a813ac029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 52,'',false,'0001',24)</value>
      <webElementGuid>ea16b76c-6a66-48f9-a4ef-68036e8e969d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>ff9587c8-77f4-4021-acba-967d5d963153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,52);</value>
      <webElementGuid>07efbb1c-626f-4e69-9a92-d6f2af4cfaef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if( !gx.evt.jsEvent(this)) return false;</value>
      <webElementGuid>74be3302-48ab-48f5-a920-7457bbe3fbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione...SINO</value>
      <webElementGuid>131b9159-6fea-41f6-9a47-494b811d5904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vCOMBO_0001&quot;)</value>
      <webElementGuid>a2b0e476-abb7-4b11-aba7-4f4fc24186ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Crear Candidatos/Page_Candidatos/iframe_Informacin Adicional Requerida_gxp0_ifrm</value>
      <webElementGuid>3caaec57-349d-4329-a713-e00c100e4c0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='vCOMBO_0001']</value>
      <webElementGuid>3b0e2f7b-b458-4e0e-9552-f3705e4c3d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TABLE_CONTAINER_TITULOFIELDCONTAINER_0001']/div[5]/select</value>
      <webElementGuid>85885af5-41db-4151-af8e-e0f34194d0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titulo'])[1]/following::select[1]</value>
      <webElementGuid>8c27aef7-a2ee-4da7-9110-1ed5b6f4cba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COLOMBIANO RETORNADO'])[1]/following::select[1]</value>
      <webElementGuid>308503e3-b4c1-4b3e-86c3-b40812953d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Si'])[1]/preceding::select[1]</value>
      <webElementGuid>8bc0f843-a571-4fbe-9035-6734858405c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combo'])[1]/preceding::select[1]</value>
      <webElementGuid>8f67cb84-8cc0-4efc-8f7e-19eb41d59ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>971264a2-469f-4330-a77a-bd4120fba7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'vCOMBO_0001' and @name = 'vCOMBO_0001' and (text() = 'Seleccione...SINO' or . = 'Seleccione...SINO')]</value>
      <webElementGuid>dbef82d5-2ae6-4f5f-9ad5-6788ed0cf0ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
