<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.SiNo</name>
   <tag></tag>
   <elementGuidId>6fe57796-5dd6-43a3-80f8-977365584b51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANINDCONDIS</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012ECANINDCONDIS&quot;)[count(. | //*[@id = 'W0031W0007W0012ECANINDCONDIS' and @name = 'W0031W0007W0012ECANINDCONDIS']) = count(//*[@id = 'W0031W0007W0012ECANINDCONDIS' and @name = 'W0031W0007W0012ECANINDCONDIS'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ECANINDCONDIS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3217778d-e075-413e-98ee-944cc097a095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANINDCONDIS</value>
      <webElementGuid>d83bd942-3c83-4d8a-9607-ca8c1a2571b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANINDCONDIS</value>
      <webElementGuid>a47d3286-28e3-4b11-851f-4d462e7eb21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>0e9abe16-8c26-4c3a-b01f-16918f19b82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(gx.evt.jsEvent(this)) {gx.evt.execCliEvt('W0026W0007W0012',false,'e110m22_client',this);} else return false;</value>
      <webElementGuid>f74c604f-3e11-4c1e-a308-e4139bce2623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 140,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>36624e39-b05b-4659-a9f1-c8ac2dd1d76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>01da4467-dfb4-4af3-a676-bd1301614530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,140);</value>
      <webElementGuid>254dd597-5eed-4bb8-b7fa-32c24832a161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Seleccione...SiNo</value>
      <webElementGuid>c51e9a80-ac14-4d7c-a4bb-f9d2fa3e817c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ECANINDCONDIS&quot;)</value>
      <webElementGuid>fa23428a-8ff7-418c-98a4-53589f9f6cba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ECANINDCONDIS']</value>
      <webElementGuid>5640f839-0b65-469d-b322-1744113bfc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012K2BTOOLSTABLE_ATTRIBUTECONTAINERECANINDCONDISFIELDCONTAINER']/div/select</value>
      <webElementGuid>4653adfd-a3da-478f-8b78-7a80f3a0155b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condición de discapacidad'])[2]/following::select[1]</value>
      <webElementGuid>9e5080ab-aebb-491d-827f-ec6c22d613e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condición de discapacidad'])[1]/following::select[1]</value>
      <webElementGuid>d0e04e0d-ccbc-4e49-9099-a5cb5e061396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discapacidades'])[1]/preceding::select[1]</value>
      <webElementGuid>3bfb3a6b-066e-480a-8f11-544875263132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condición Laboral'])[1]/preceding::select[1]</value>
      <webElementGuid>5798b622-6dca-46e6-905f-305ab38d610b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div[2]/div/div/select</value>
      <webElementGuid>9483ae47-cded-4b28-9c79-e68fb098964a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ECANINDCONDIS' and @name = 'W0026W0007W0012ECANINDCONDIS' and (text() = '
Seleccione...SiNo' or . = '
Seleccione...SiNo')]</value>
      <webElementGuid>e60f59a3-0d23-4b35-8802-3421c304cedd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
