<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.AMAZONASANTIOQUIAARAUCAAT_c008ef_1</name>
   <tag></tag>
   <elementGuidId>461fe757-391b-49a5-8673-c4e1caafb4a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012vDEPSECNAC</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012vDEPSECNAC&quot;)[count(. | //*[@id = 'W0031W0007W0012vDEPSECNAC' and @name = 'W0026W0007W0012vDEPSECNAC']) = count(//*[@id = 'W0031W0007W0012vDEPSECNAC' and @name = 'W0026W0007W0012vDEPSECNAC'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0031W0007W0012vDEPSECNAC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23c979ea-5873-41a5-b75a-231dcc9d0cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012vDEPSECNAC</value>
      <webElementGuid>00ddc616-b776-4b8d-a5a7-dea9d8ce1448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012vDEPSECNAC</value>
      <webElementGuid>85496c08-ec59-4e8e-9998-79dd42339a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>28fc6767-a479-4045-be08-709acbbbdf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>4733d320-9e72-44c1-b188-368bd3583ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 103,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>b98a8253-5fc0-40b9-b89a-a0d0eb14e4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>6e1c6290-ef69-498f-99a1-c7bf10d27086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,103);</value>
      <webElementGuid>9fdaeca2-5e64-4fed-8595-ab9557f9d26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9a0235ac-b0ac-42a6-9f18-9f22a5eb3ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3e6c6ef9-663a-4b03-9f47-6369e18fd64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Seleccione...AMAZONASANTIOQUIAARAUCAATLÁNTICOBOGOTÁBOLÍVARBOYACÁCALDASCAQUETÁCASANARECAUCACESARCHOCÓCUNDINAMARCACÓRDOBAGUAINÍAGUAVIAREHUILALA GUAJIRAMAGDALENAMETANARIÑONORTE DE SANTANDERPUTUMAYOQUINDÍORISARALDASAN ANDRES Y PROVIDENCIASANTANDERSUCRETOLIMAVALLE DEL CAUCAVAUPÉSVICHADA</value>
      <webElementGuid>5d9172f7-a2fa-468b-8b11-ab82d385cdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012vDEPSECNAC&quot;)</value>
      <webElementGuid>c4e8c54a-c2dd-44b7-aa38-89f12db5a605</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012vDEPSECNAC']</value>
      <webElementGuid>6aee3716-09ad-42e6-b00d-33168a08ba75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[7]/div[2]/div/div/select</value>
      <webElementGuid>1116f604-e5eb-4c5d-8c1a-eb33cf4fff7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento Nacimiento'])[1]/following::select[1]</value>
      <webElementGuid>f2105c2a-c9ae-494b-a410-d9197dd5326f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País Nacimiento'])[1]/following::select[2]</value>
      <webElementGuid>acf0f33a-627d-409f-ab14-ec26586c1133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Municipio Nacimiento'])[1]/preceding::select[1]</value>
      <webElementGuid>b6da4bb8-ab16-4bd5-b075-a03953dadf2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comunidad LGBTI'])[1]/preceding::select[2]</value>
      <webElementGuid>5b13b11b-8dcd-4473-a447-da65da9d7eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/select</value>
      <webElementGuid>c02e0b5e-be1a-41d0-8492-67679a5c3eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012vDEPSECNAC' and @name = 'W0026W0007W0012vDEPSECNAC' and (text() = '
Seleccione...AMAZONASANTIOQUIAARAUCAATLÁNTICOBOGOTÁBOLÍVARBOYACÁCALDASCAQUETÁCASANARECAUCACESARCHOCÓCUNDINAMARCACÓRDOBAGUAINÍAGUAVIAREHUILALA GUAJIRAMAGDALENAMETANARIÑONORTE DE SANTANDERPUTUMAYOQUINDÍORISARALDASAN ANDRES Y PROVIDENCIASANTANDERSUCRETOLIMAVALLE DEL CAUCAVAUPÉSVICHADA' or . = '
Seleccione...AMAZONASANTIOQUIAARAUCAATLÁNTICOBOGOTÁBOLÍVARBOYACÁCALDASCAQUETÁCASANARECAUCACESARCHOCÓCUNDINAMARCACÓRDOBAGUAINÍAGUAVIAREHUILALA GUAJIRAMAGDALENAMETANARIÑONORTE DE SANTANDERPUTUMAYOQUINDÍORISARALDASAN ANDRES Y PROVIDENCIASANTANDERSUCRETOLIMAVALLE DEL CAUCAVAUPÉSVICHADA')]</value>
      <webElementGuid>b347f40b-38bf-47f0-961e-5b13a145ccce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
