<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.EMPLEADOEN BSQUEDA DE EMP_3a53bd</name>
   <tag></tag>
   <elementGuidId>bd43f005-2768-43b5-9fcd-ecc08538d53b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECONLABSEC</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012ECONLABSEC&quot;)[count(. | //*[@id = 'W0031W0007W0012ECONLABSEC' and @name = 'W0031W0007W0012ECONLABSEC']) = count(//*[@id = 'W0031W0007W0012ECONLABSEC' and @name = 'W0031W0007W0012ECONLABSEC'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ECONLABSEC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3f96dc35-85ed-4f0c-b484-23c3e30f5975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ECONLABSEC</value>
      <webElementGuid>9dc41c14-d61c-45ee-b1bf-89a675ae32b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ECONLABSEC</value>
      <webElementGuid>63b84794-0331-4d8d-b2b5-3e89023cc0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>df347e34-41f3-42c3-8a4c-4d0264c7bb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>3819074a-0a74-41d8-9596-506f69543b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 150,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>4021d9c1-2d8a-48cc-839c-01643a535e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>9a239d66-f8c4-4cba-9688-b79156dec09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,150);</value>
      <webElementGuid>0c7f15fb-2040-424e-acf8-a14049b3cdd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>75499aa8-92a5-40f6-a856-bf6deedd1ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
...Seleccione...EMPLEADOEN BÚSQUEDA DE EMPLEOINDEPENDIENTE</value>
      <webElementGuid>43c118d8-ac21-4580-b348-836cc9ea9d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ECONLABSEC&quot;)</value>
      <webElementGuid>396eef34-b74d-403a-b3f1-4abb797bcdf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ECONLABSEC']</value>
      <webElementGuid>d1d34c98-8cc3-4115-9652-ce9be213eeef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[12]/div/div/div/select</value>
      <webElementGuid>7db3e234-659f-42cb-bf99-89ee71e7a308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condición Laboral'])[1]/following::select[1]</value>
      <webElementGuid>0759a008-4295-43cd-bbfc-2113292feef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discapacidades'])[1]/following::select[1]</value>
      <webElementGuid>9923cd2e-d6c5-4a59-9f76-df3719685b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empleado Sena'])[1]/preceding::select[1]</value>
      <webElementGuid>a592860f-20cc-46b9-a770-ceea370a4966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Empleado'])[1]/preceding::select[2]</value>
      <webElementGuid>b574cf7c-b830-4765-a323-457357201b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/select</value>
      <webElementGuid>27301836-9761-4234-9ab6-00fea368e921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ECONLABSEC' and @name = 'W0026W0007W0012ECONLABSEC' and (text() = '
...Seleccione...EMPLEADOEN BÚSQUEDA DE EMPLEOINDEPENDIENTE' or . = '
...Seleccione...EMPLEADOEN BÚSQUEDA DE EMPLEOINDEPENDIENTE')]</value>
      <webElementGuid>33280b7c-1f97-4fb7-9503-8293b988cd63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
