<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.ABAB-AA-BB-OO-</name>
   <tag></tag>
   <elementGuidId>8b9b2f6d-ef75-48a8-9a75-aa249c98062d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANGRUSAN</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012ECANGRUSAN&quot;)[count(. | //*[@id = 'W0031W0007W0012ECANGRUSAN' and @name = 'W0031W0007W0012ECANGRUSAN' and (text() = '
...Seleccione...AB+AB-A+A-B+B-O+O-' or . = '
...Seleccione...AB+AB-A+A-B+B-O+O-')]) = count(//*[@id = 'W0031W0007W0012ECANGRUSAN' and @name = 'W0031W0007W0012ECANGRUSAN' and (text() = '
...Seleccione...AB+AB-A+A-B+B-O+O-' or . = '
...Seleccione...AB+AB-A+A-B+B-O+O-')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ECANGRUSAN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cdcb757a-c298-48a7-86b9-aff111621aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANGRUSAN</value>
      <webElementGuid>8d86dcb7-428f-4f81-8625-8ed510b468cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANGRUSAN</value>
      <webElementGuid>844e1428-1ba3-4307-bf6b-f87bb3bf2303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>d8299ea2-6ff0-4e42-b11c-48cc29d13c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>992b0893-263a-4df0-906b-1229928f2458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 76,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>2873d964-0449-48a4-9dfd-b77c4ec63d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>735a0def-1d46-4f8b-a218-aa30910adbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,76);</value>
      <webElementGuid>7d04336a-b3da-4275-bdb3-08e651d43046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
...Seleccione...AB+AB-A+A-B+B-O+O-</value>
      <webElementGuid>b68e5744-88ef-4af1-a224-1aef2f05c08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ECANGRUSAN&quot;)</value>
      <webElementGuid>f8a27de7-fee3-42f9-9197-5155366767a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ECANGRUSAN']</value>
      <webElementGuid>bc2a3eaf-1b77-45c8-b1b2-077f30d451d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[4]/div/div/div/select</value>
      <webElementGuid>fe714766-aede-4c1b-848f-115a26d65906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo Sanguineo'])[1]/following::select[1]</value>
      <webElementGuid>72805981-03e6-487b-8667-ff8026a3b1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Género'])[1]/following::select[2]</value>
      <webElementGuid>141baede-cfc7-495c-b325-f15a9ecf4a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País Expedición'])[1]/preceding::select[1]</value>
      <webElementGuid>9768f51c-ba44-4763-bbb6-403ad1034963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento Expedición'])[1]/preceding::select[2]</value>
      <webElementGuid>65451461-9482-4131-aaa1-8de970bbce03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/select</value>
      <webElementGuid>3bf0d163-014b-41b9-9684-6c222e25c8f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ECANGRUSAN' and @name = 'W0026W0007W0012ECANGRUSAN' and (text() = '
...Seleccione...AB+AB-A+A-B+B-O+O-' or . = '
...Seleccione...AB+AB-A+A-B+B-O+O-')]</value>
      <webElementGuid>a2332e04-e58f-4aa3-b107-c6bbcb22d3d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
