<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.CCCEEINTAX IDNITPEPPPTPSTI</name>
   <tag></tag>
   <elementGuidId>d20cec33-0631-48ba-a471-ccb0a6f92f21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ECANTIPIDESEC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANTIPIDESEC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c9601908-e466-4572-b4d0-55c8a21f357c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012ECANTIPIDESEC</value>
      <webElementGuid>5309df10-f801-4e96-9651-83366224d4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012ECANTIPIDESEC</value>
      <webElementGuid>99fdf0c0-0012-4701-ad01-f79210e01c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn form-control</value>
      <webElementGuid>da20f8b0-8e28-4129-845f-467eddfb34b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>99b88175-4b0e-4c8d-b304-2b6be578144a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 39,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>26ecbccc-d7a1-4a6b-ba87-c33ee88af6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>ea3cbccc-d978-4ebf-98be-621e1376840b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,39);</value>
      <webElementGuid>49a2fdd0-3586-40de-ac8b-e9560364c8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
...Seleccione...CCCEEIN/TAX IDNITPEPPPTPSTI</value>
      <webElementGuid>dd4924a8-8c78-4a2d-a4fe-5dd7198ff1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012ECANTIPIDESEC&quot;)</value>
      <webElementGuid>0541dba0-6bac-4183-9940-a0097621e9bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ECANTIPIDESEC']</value>
      <webElementGuid>700889a7-7ce8-4dc1-a8ba-352ea26a5e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012K2BTOOLSTABLE_ATTRIBUTECONTAINERECANTIPIDESECFIELDCONTAINER']/div/select</value>
      <webElementGuid>902372c2-d9b0-43c4-a218-2ffe6f1aae40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Identificación'])[1]/following::select[1]</value>
      <webElementGuid>c03f4bf5-2b25-4c2e-9530-0218c76448ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Identificación*'])[1]/following::select[1]</value>
      <webElementGuid>027eea3b-3829-4730-8e26-38f7a2daf09a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número Identificación'])[1]/preceding::select[1]</value>
      <webElementGuid>cde73931-9aec-485c-a1c2-e543e057e2ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primer Nombre'])[1]/preceding::select[1]</value>
      <webElementGuid>75a6c31a-b155-40c4-aa4e-fa89e35994b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>087626ec-9099-42fc-bf6e-d9b9597446d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ECANTIPIDESEC' and @name = 'W0026W0007W0012ECANTIPIDESEC' and (text() = '
...Seleccione...CCCEEIN/TAX IDNITPEPPPTPSTI' or . = '
...Seleccione...CCCEEIN/TAX IDNITPEPPPTPSTI')]</value>
      <webElementGuid>81c47401-e6fd-4711-a5de-24253ad56d43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
