<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.AGUADAALBANIAARATOCABARBO_f6a42f</name>
   <tag></tag>
   <elementGuidId>04b897ac-1f5b-46bf-8716-5f71e94c7392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ECANEXPMUNSEC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANEXPMUNSEC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ee28724a-5280-4224-afd3-0e7691c8e7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012ECANEXPMUNSEC</value>
      <webElementGuid>08aafc79-0aa0-4a83-89cf-194125b112a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012ECANEXPMUNSEC</value>
      <webElementGuid>403324eb-2145-4176-95ce-1578b9555c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>6f422d72-456c-451c-9479-4dcab7f20e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>b8b0d2f5-f8ce-43a3-9579-379f2bfce1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 90,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>d28a877d-eab9-42f6-9b5a-26cc15a76a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>bfe9155a-cd69-4129-9fd9-18ba5b5fdda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,90);</value>
      <webElementGuid>e81852be-d649-4c7a-beb1-bc3c1def4d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b013076a-2035-4d93-98a3-6e6a3a9fd0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>67c71ff2-1e11-4e25-b6c7-21306848b614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Seleccione...AGUADAALBANIAARATOCABARBOSABARICHARABARRANCABERMEJABETULIABOLÍVARBUCARAMANGACABRERACALIFORNIACAPITANEJOCARCASÍCEPITÁCERRITOCHARALÁCHARTACHIMACHIPATÁCIMITARRACONCEPCIÓNCONFINESCONTRATACIÓNCOROMOROCURITÍEL CARMEN DE CHUCURÍEL GUACAMAYOEL PEÑÓNEL PLAYÓNENCINOENCISOFLORIDABLANCAFLORIÁNGALÁNGIRÓNGUACAGUADALUPEGUAPOTÁGUAVATÁGÁMBITAGÜEPSAHATOJESÚS MARÍAJORDÁNLA BELLEZALA PAZLANDAZURILEBRIJALOS SANTOSMACARAVITAMATANZAMOGOTESMOLAGAVITAMÁLAGAOCAMONTEOIBAONZAGAPALMARPALMAS DEL SOCORROPIEDECUESTAPINCHOTEPUENTE NACIONALPUERTO PARRAPUERTO WILCHESPÁRAMORIONEGROSABANA DE TORRESSAN ANDRÉSSAN BENITOSAN GILSAN JOAQUÍNSAN JOSÉ DE MIRANDASAN MIGUELSAN VICENTE DE CHUCURÍSANTA BÁRBARASANTA HELENA DEL OPÓNSIMACOTASOCORROSUAITASUCRESURATÁTONAVALLE DE SAN JOSÉVETASVILLANUEVAVÉLEZZAPATOCA</value>
      <webElementGuid>db514c7c-f285-492a-9549-57e4dfcaf1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012ECANEXPMUNSEC&quot;)</value>
      <webElementGuid>a191ed69-1907-48be-8e14-41867361f9d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ECANEXPMUNSEC']</value>
      <webElementGuid>95e11eeb-971d-442a-b572-a42b502c2089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[6]/div/div/div/select</value>
      <webElementGuid>82238dc7-f392-4464-b26e-25e08f15c7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciudad Expedición'])[1]/following::select[1]</value>
      <webElementGuid>567f2495-632e-4127-8c63-8090562209ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento Expedición'])[1]/following::select[2]</value>
      <webElementGuid>29326791-5927-417e-b8aa-510a46bb8043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Expedición*'])[1]/preceding::select[1]</value>
      <webElementGuid>e00e80ed-de4e-41c7-8602-ab192900fee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País Nacimiento'])[1]/preceding::select[1]</value>
      <webElementGuid>fbcb5225-3e81-4c88-8b8b-34e70f2e3b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/select</value>
      <webElementGuid>91797878-d9ea-43aa-932e-5a9e1772f879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ECANEXPMUNSEC' and @name = 'W0026W0007W0012ECANEXPMUNSEC' and (text() = '
Seleccione...AGUADAALBANIAARATOCABARBOSABARICHARABARRANCABERMEJABETULIABOLÍVARBUCARAMANGACABRERACALIFORNIACAPITANEJOCARCASÍCEPITÁCERRITOCHARALÁCHARTACHIMACHIPATÁCIMITARRACONCEPCIÓNCONFINESCONTRATACIÓNCOROMOROCURITÍEL CARMEN DE CHUCURÍEL GUACAMAYOEL PEÑÓNEL PLAYÓNENCINOENCISOFLORIDABLANCAFLORIÁNGALÁNGIRÓNGUACAGUADALUPEGUAPOTÁGUAVATÁGÁMBITAGÜEPSAHATOJESÚS MARÍAJORDÁNLA BELLEZALA PAZLANDAZURILEBRIJALOS SANTOSMACARAVITAMATANZAMOGOTESMOLAGAVITAMÁLAGAOCAMONTEOIBAONZAGAPALMARPALMAS DEL SOCORROPIEDECUESTAPINCHOTEPUENTE NACIONALPUERTO PARRAPUERTO WILCHESPÁRAMORIONEGROSABANA DE TORRESSAN ANDRÉSSAN BENITOSAN GILSAN JOAQUÍNSAN JOSÉ DE MIRANDASAN MIGUELSAN VICENTE DE CHUCURÍSANTA BÁRBARASANTA HELENA DEL OPÓNSIMACOTASOCORROSUAITASUCRESURATÁTONAVALLE DE SAN JOSÉVETASVILLANUEVAVÉLEZZAPATOCA' or . = '
Seleccione...AGUADAALBANIAARATOCABARBOSABARICHARABARRANCABERMEJABETULIABOLÍVARBUCARAMANGACABRERACALIFORNIACAPITANEJOCARCASÍCEPITÁCERRITOCHARALÁCHARTACHIMACHIPATÁCIMITARRACONCEPCIÓNCONFINESCONTRATACIÓNCOROMOROCURITÍEL CARMEN DE CHUCURÍEL GUACAMAYOEL PEÑÓNEL PLAYÓNENCINOENCISOFLORIDABLANCAFLORIÁNGALÁNGIRÓNGUACAGUADALUPEGUAPOTÁGUAVATÁGÁMBITAGÜEPSAHATOJESÚS MARÍAJORDÁNLA BELLEZALA PAZLANDAZURILEBRIJALOS SANTOSMACARAVITAMATANZAMOGOTESMOLAGAVITAMÁLAGAOCAMONTEOIBAONZAGAPALMARPALMAS DEL SOCORROPIEDECUESTAPINCHOTEPUENTE NACIONALPUERTO PARRAPUERTO WILCHESPÁRAMORIONEGROSABANA DE TORRESSAN ANDRÉSSAN BENITOSAN GILSAN JOAQUÍNSAN JOSÉ DE MIRANDASAN MIGUELSAN VICENTE DE CHUCURÍSANTA BÁRBARASANTA HELENA DEL OPÓNSIMACOTASOCORROSUAITASUCRESURATÁTONAVALLE DE SAN JOSÉVETASVILLANUEVAVÉLEZZAPATOCA')]</value>
      <webElementGuid>241c4c70-3825-49f8-8202-894e6dccaf91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
