<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.SiNo_1</name>
   <tag></tag>
   <elementGuidId>34caf0c1-a820-43a9-b4ae-aaa765b1bf57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANEMPSEN</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'W0031W0007W0012ECANEMPSEN' and @name = 'W0031W0007W0012ECANEMPSEN' and (text() = '
Seleccione...SiNo' or . = '
Seleccione...SiNo')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ECANEMPSEN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>97ff2a07-c629-4115-994e-97861fd2138d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANEMPSEN</value>
      <webElementGuid>b9f4bd85-e8fb-4fc6-a4ce-ef0cc97b90e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ECANEMPSEN</value>
      <webElementGuid>603b3fea-c5c4-4236-88ea-5a1f69020bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>94780d6d-633c-4ed3-9272-78f268d5795e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>450e92d4-5f34-4062-ac87-46d7de708bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 155,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>a9de6366-6a33-4f29-95fc-8a9acb7cd850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>71d29811-214f-4aa1-a258-fb217267432e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,155);</value>
      <webElementGuid>9498daba-d251-49a3-9d8d-6cd06d54a6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Seleccione...SiNo</value>
      <webElementGuid>2e7ba73d-5b3b-4810-b863-896237019d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ECANEMPSEN&quot;)</value>
      <webElementGuid>148034c7-6dbc-481e-90c9-769f77c712e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ECANEMPSEN']</value>
      <webElementGuid>d086a3b9-0718-4404-a92e-f4e3bf4bfb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[13]/div/div/div/select</value>
      <webElementGuid>24ae3306-fa59-422a-acf9-21387949057d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empleado Sena'])[1]/following::select[1]</value>
      <webElementGuid>41bf53f2-1e4d-4170-b336-6c96d69f2f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condición Laboral'])[1]/following::select[2]</value>
      <webElementGuid>0d30a0f3-1120-4a0e-bd78-e6367315541f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Empleado'])[1]/preceding::select[1]</value>
      <webElementGuid>cd111c28-9bca-4393-84ad-6549d241b42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EncontroCRM'])[1]/preceding::select[2]</value>
      <webElementGuid>513ea211-106f-48d1-bf10-4abda2299fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div/select</value>
      <webElementGuid>90e41d9f-69f6-4715-90f2-a1890ad0489d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ECANEMPSEN' and @name = 'W0026W0007W0012ECANEMPSEN' and (text() = '
Seleccione...SiNo' or . = '
Seleccione...SiNo')]</value>
      <webElementGuid>fcc81e8d-2f2b-4ed5-be24-48956e4983b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
