<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.CASADOINDIFERENTESEPARADO_cdd702</name>
   <tag></tag>
   <elementGuidId>cae2b8ae-4ad0-493e-8533-8b2faf036ea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ESTCIVSEC</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012ESTCIVSEC&quot;)[count(. | //*[@id = 'W0031W0007W0012ESTCIVSEC' and @name = 'W0031W0007W0012ESTCIVSEC']) = count(//*[@id = 'W0031W0007W0012ESTCIVSEC' and @name = 'W0031W0007W0012ESTCIVSEC'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ESTCIVSEC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>18c4620c-d4f5-4fe2-a32b-f18180eba5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ESTCIVSEC</value>
      <webElementGuid>5c0a0bba-799e-43fc-8f34-fc25f10b6aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ESTCIVSEC</value>
      <webElementGuid>b05957d0-91b2-498e-89ed-51cf42ebfb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>57a13250-fd9e-408f-8aee-22394fe0596a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>107ef512-93d5-49ec-a716-3c5c10f05598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 121,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>e5450b58-d618-4228-883a-1d35df929785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>24213245-33e5-4e39-8d84-e99d0fccc510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,121);</value>
      <webElementGuid>06256d48-1d7b-4ba9-933b-7eb4655f0fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1748a744-9efb-42b0-ba37-880d142f223e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
...Seleccione...CASADOINDIFERENTESEPARADOSOLTEROUNIÓN LIBREVIUDO</value>
      <webElementGuid>aa558034-5c2e-46e7-a8eb-b4ee220a1741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ESTCIVSEC&quot;)</value>
      <webElementGuid>fc6778d3-be3c-4017-a305-6eed2480dfc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ESTCIVSEC']</value>
      <webElementGuid>172a2d07-a1d0-423c-aabb-baa3e48785a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[9]/div[2]/div/div/select</value>
      <webElementGuid>a712beec-c217-454c-b2a6-a65f50bc97d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado civil'])[1]/following::select[1]</value>
      <webElementGuid>d9e0413e-c306-4b85-8adc-51875f539680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libreta Militar'])[1]/following::select[1]</value>
      <webElementGuid>6fb3d2d5-c29a-493c-af33-f4ad41ccaa1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel de Escolaridad'])[1]/preceding::select[1]</value>
      <webElementGuid>4aad8abf-ca05-41db-9501-f59502324888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Población'])[1]/preceding::select[2]</value>
      <webElementGuid>d3e964e2-6da5-4517-bae2-ce4a251380cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/select</value>
      <webElementGuid>c1498a2c-a454-4305-94dc-9c5221e25c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ESTCIVSEC' and @name = 'W0026W0007W0012ESTCIVSEC' and (text() = '
...Seleccione...CASADOINDIFERENTESEPARADOSOLTEROUNIÓN LIBREVIUDO' or . = '
...Seleccione...CASADOINDIFERENTESEPARADOSOLTEROUNIÓN LIBREVIUDO')]</value>
      <webElementGuid>fd09cd07-cf78-467e-82c8-04445d7aaaf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
