<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.TRESCUATROCINCOUNODOSSEIS</name>
   <tag></tag>
   <elementGuidId>286ccc62-c546-486a-8cdd-f194cf851bbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ESTSEC</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;W0031W0007W0012ESTSEC&quot;)[count(. | //*[@id = 'W0031W0007W0012ESTSEC' and @name = 'W0031W0007W0012ESTSEC']) = count(//*[@id = 'W0031W0007W0012ESTSEC' and @name = 'W0031W0007W0012ESTSEC'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ESTSEC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23ea9893-3fe0-41d5-ae31-f7d654cadbe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0031W0007W0012ESTSEC</value>
      <webElementGuid>34afa825-3c0b-430e-a3e6-ad1781458a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0031W0007W0012ESTSEC</value>
      <webElementGuid>db4242f3-60ea-4a9a-9e49-bf8afb39c5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>7700b4d6-2390-418b-aab4-58d4c65395eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>1a2a4b86-aee8-4682-9a37-583ae8108fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 263,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>c40d15e2-d5eb-4784-9c20-f8d70971754f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>f684348d-052e-44b6-b57c-abadd60fdc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,263);</value>
      <webElementGuid>ef2de292-2936-4cf4-8142-05b3ece3e127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f61a3f61-d5c9-4d3b-91ce-d10ac310d5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
...Seleccione...TRESCUATROCINCOUNODOSSEIS</value>
      <webElementGuid>bcdc12a2-20a4-41fe-b1f0-c1b6bf4e438f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0031W0007W0012ESTSEC&quot;)</value>
      <webElementGuid>66f36cb2-d5bd-4cd5-aa8d-108814cee3a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ESTSEC']</value>
      <webElementGuid>f4854edc-439b-4a75-b4af-1f381d638e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP3TABLECONTENT']/div[3]/div[2]/div/div/select</value>
      <webElementGuid>36885870-bb8a-446d-a1ba-4dfc9a9d7664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estrato'])[1]/following::select[1]</value>
      <webElementGuid>8c3c400b-d38c-41ff-9f30-46a0ecfe396e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Municipio Residencia'])[1]/following::select[2]</value>
      <webElementGuid>64d0a75c-43dd-4ebb-81c1-a3e47adf7c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teléfono'])[1]/preceding::select[1]</value>
      <webElementGuid>d4617c12-ed68-4184-bff3-b72b4d9e2268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Celular'])[1]/preceding::select[1]</value>
      <webElementGuid>35c559be-99c1-4805-9253-2f30c29b0f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/select</value>
      <webElementGuid>3fa0adbe-ba5b-4712-a184-32a8c3218f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ESTSEC' and @name = 'W0026W0007W0012ESTSEC' and (text() = '
...Seleccione...TRESCUATROCINCOUNODOSSEIS' or . = '
...Seleccione...TRESCUATROCINCOUNODOSSEIS')]</value>
      <webElementGuid>5e703e9b-96f1-487c-99bd-35b196e865d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
