<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.NINGUNOPRIMARIAMEDIABACHI_b4fc22</name>
   <tag></tag>
   <elementGuidId>3bf49e8b-d5be-46cb-afc3-fe1351bb3626</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ENIVESCSEC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ENIVESCSEC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0f4d1163-cd38-4fcd-b744-cbda76fff70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012ENIVESCSEC</value>
      <webElementGuid>8e7c5354-6019-4912-8070-a8f182ada4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012ENIVESCSEC</value>
      <webElementGuid>b672debb-bf40-46f7-8982-8c9caf8c28d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>531444ef-f54e-4250-911d-becac441c409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>81d9dcad-2ddf-461d-85c0-a27326155530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 126,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>7ee9c61e-6ab0-46e6-9733-81fe9c3d5f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>d7d40838-4c0a-4a40-82e3-e2b0b0d0c75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,126);</value>
      <webElementGuid>59082404-fc8b-44c9-afe7-709afefd7665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>11f30757-4953-4c6d-a4fc-83a645f56f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
...Seleccione...NINGUNOPRIMARIAMEDIABACHILLERTÉCNICOTECNÓLOGOPROFESIONALESPECIALIZACIÓNMAESTRÍADOCTORADO</value>
      <webElementGuid>ba5eebc0-a89d-451b-b728-c622aa046bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012ENIVESCSEC&quot;)</value>
      <webElementGuid>240718a5-9e3d-410e-ad59-b5b7962023a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ENIVESCSEC']</value>
      <webElementGuid>9ea6a9f0-560b-4bc1-b71e-5238bb07c737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP0TABLECONTENT']/div[10]/div/div/div/select</value>
      <webElementGuid>6f9c76ce-569b-4b94-a70e-908dcffa3163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel de Escolaridad'])[1]/following::select[1]</value>
      <webElementGuid>e516f949-afca-4578-94ec-f5257e5c3af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado civil'])[1]/following::select[2]</value>
      <webElementGuid>eb8d640b-303b-4afe-8b23-b3a3519e1a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Población'])[1]/preceding::select[1]</value>
      <webElementGuid>554bb36a-cf34-4f9c-807f-d2261245fa6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condición de discapacidad'])[1]/preceding::select[2]</value>
      <webElementGuid>a9408021-1655-4233-8288-a28ec01f03a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/select</value>
      <webElementGuid>33c2a20a-b251-4a23-9b88-5ee90528802f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ENIVESCSEC' and @name = 'W0026W0007W0012ENIVESCSEC' and (text() = '
...Seleccione...NINGUNOPRIMARIAMEDIABACHILLERTÉCNICOTECNÓLOGOPROFESIONALESPECIALIZACIÓNMAESTRÍADOCTORADO' or . = '
...Seleccione...NINGUNOPRIMARIAMEDIABACHILLERTÉCNICOTECNÓLOGOPROFESIONALESPECIALIZACIÓNMAESTRÍADOCTORADO')]</value>
      <webElementGuid>1575aa18-699c-450c-8987-0c30f48f0a7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
