<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.ABEJORRALABRIAQUALEJANDRA_874242</name>
   <tag></tag>
   <elementGuidId>2f4d401a-4178-4fe8-83c2-0b4fecd8a5e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012ECANRESMUNSEC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012ECANRESMUNSEC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1c339cfb-687c-4c9a-917b-7738934a0d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012ECANRESMUNSEC</value>
      <webElementGuid>401d0626-24c5-483d-8987-427d92548bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012ECANRESMUNSEC</value>
      <webElementGuid>ad650d11-df16-402f-8515-f1f2ddbfd40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Required form-control</value>
      <webElementGuid>7ed4fdc0-2c07-48bb-9c0e-2e3b1fe3f63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>0426161d-b4c6-481a-8aa3-1784457d2ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 259,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>c4cf60a3-ec5d-48f5-9421-ad2e6e579189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>834714bc-6ddd-4bb2-a272-f693bd552a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,259);</value>
      <webElementGuid>13138135-fd49-453a-bb6b-15dae8fb3f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f9298fc4-d71f-440c-b1ba-b144e1926214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e3fafe90-c51c-4460-b22a-daf69756b505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Seleccione...ABEJORRALABRIAQUÍALEJANDRÍAAMAGÁAMALFIANDESANGELÓPOLISANGOSTURAANORÍANZÁAPARTADÓARBOLETESARGELIAARMENIABARBOSABELLOBELMIRABETANIABETULIABRICEÑOBURITICÁCAICEDOCALDASCAMPAMENTOCARACOLÍCARAMANTACAREPACAROLINACAUCASIACAÑASGORDASCHIGORODÓCISNEROSCIUDAD BOLÍVARCOCORNÁCONCEPCIÓNCONCORDIACOPACABANACÁCERESDABEIBADON MATÍASEBÉJICOEL BAGREEL CARMEN DE VIBORALEL SANTUARIOENGATIVAENTRERRÍOSENVIGADOFREDONIAFRONTINOGIRALDOGIRARDOTAGRANADAGUADALUPEGUARNEGUATAPÉGÓMEZ PLATAHELICONIAHISPANIAITAGÜÍITUANGOJARDÍNJERICÓLA CEJALA ESTRELLALA PINTADALA UNIÓNLIBORINAMACEOMARINILLAMEDELLÍNMONTEBELLOMURINDÓMUTATÁNARIÑONECHÍNECOCLÍOLAYAPEQUEPEÑOLPUEBLORRICOPUERTO BERRÍOPUERTO NAREPUERTO TRIUNFOREMEDIOSRETIRORIONEGROSABANALARGASABANETASALGARSAN ANDRÉS DE CUERQUIASAN CARLOSSAN FRANCISCOSAN JERÓNIMOSAN JOSÉ DE LA MONTAÑASAN JUAN DE URABÁSAN LUISSAN PEDROSAN PEDRO DE URABÁSAN RAFAELSAN ROQUESAN VICENTESANTA BÁRBARASANTA ROSA DE OSOSSANTAFÉ DE ANTIOQUIASANTO DOMINGOSEGOVIASONSÓNSOPETRÁNTARAZÁTARSOTITIRIBÍTOLEDOTURBOTÁMESISURAMITAURRAOVALDIVIAVALPARAÍSOVEGACHÍVENECIAVIGÍA DEL FUERTEYALÍYARUMALYOLOMBÓYONDÓZARAGOZA</value>
      <webElementGuid>3e98de74-5d80-4a16-b9d3-fa220e7f3793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012ECANRESMUNSEC&quot;)</value>
      <webElementGuid>4553026f-8629-40eb-899b-8ac24e2820df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012ECANRESMUNSEC']</value>
      <webElementGuid>7c742e0a-db82-486b-9e4c-49776101a45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012GROUP3TABLECONTENT']/div[3]/div/div/div/select</value>
      <webElementGuid>df8fee48-3d92-4634-9c70-5ecdd377395f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Municipio Residencia'])[1]/following::select[1]</value>
      <webElementGuid>360c78af-04dc-4afc-bf43-cf0cbaea57e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento Residencia'])[1]/following::select[2]</value>
      <webElementGuid>5b53e5a2-09a6-4c8a-9731-b19783d812db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estrato'])[1]/preceding::select[1]</value>
      <webElementGuid>4a2ebfa0-b181-4874-a8ed-4b238dda4699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teléfono'])[1]/preceding::select[2]</value>
      <webElementGuid>dfcdf52d-578e-49a7-a777-39f1eb749fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/fieldset/div/div[3]/div/div/div/select</value>
      <webElementGuid>aee78216-6e84-456d-bd87-3318c63113d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012ECANRESMUNSEC' and @name = 'W0026W0007W0012ECANRESMUNSEC' and (text() = '
Seleccione...ABEJORRALABRIAQUÍALEJANDRÍAAMAGÁAMALFIANDESANGELÓPOLISANGOSTURAANORÍANZÁAPARTADÓARBOLETESARGELIAARMENIABARBOSABELLOBELMIRABETANIABETULIABRICEÑOBURITICÁCAICEDOCALDASCAMPAMENTOCARACOLÍCARAMANTACAREPACAROLINACAUCASIACAÑASGORDASCHIGORODÓCISNEROSCIUDAD BOLÍVARCOCORNÁCONCEPCIÓNCONCORDIACOPACABANACÁCERESDABEIBADON MATÍASEBÉJICOEL BAGREEL CARMEN DE VIBORALEL SANTUARIOENGATIVAENTRERRÍOSENVIGADOFREDONIAFRONTINOGIRALDOGIRARDOTAGRANADAGUADALUPEGUARNEGUATAPÉGÓMEZ PLATAHELICONIAHISPANIAITAGÜÍITUANGOJARDÍNJERICÓLA CEJALA ESTRELLALA PINTADALA UNIÓNLIBORINAMACEOMARINILLAMEDELLÍNMONTEBELLOMURINDÓMUTATÁNARIÑONECHÍNECOCLÍOLAYAPEQUEPEÑOLPUEBLORRICOPUERTO BERRÍOPUERTO NAREPUERTO TRIUNFOREMEDIOSRETIRORIONEGROSABANALARGASABANETASALGARSAN ANDRÉS DE CUERQUIASAN CARLOSSAN FRANCISCOSAN JERÓNIMOSAN JOSÉ DE LA MONTAÑASAN JUAN DE URABÁSAN LUISSAN PEDROSAN PEDRO DE URABÁSAN RAFAELSAN ROQUESAN VICENTESANTA BÁRBARASANTA ROSA DE OSOSSANTAFÉ DE ANTIOQUIASANTO DOMINGOSEGOVIASONSÓNSOPETRÁNTARAZÁTARSOTITIRIBÍTOLEDOTURBOTÁMESISURAMITAURRAOVALDIVIAVALPARAÍSOVEGACHÍVENECIAVIGÍA DEL FUERTEYALÍYARUMALYOLOMBÓYONDÓZARAGOZA' or . = '
Seleccione...ABEJORRALABRIAQUÍALEJANDRÍAAMAGÁAMALFIANDESANGELÓPOLISANGOSTURAANORÍANZÁAPARTADÓARBOLETESARGELIAARMENIABARBOSABELLOBELMIRABETANIABETULIABRICEÑOBURITICÁCAICEDOCALDASCAMPAMENTOCARACOLÍCARAMANTACAREPACAROLINACAUCASIACAÑASGORDASCHIGORODÓCISNEROSCIUDAD BOLÍVARCOCORNÁCONCEPCIÓNCONCORDIACOPACABANACÁCERESDABEIBADON MATÍASEBÉJICOEL BAGREEL CARMEN DE VIBORALEL SANTUARIOENGATIVAENTRERRÍOSENVIGADOFREDONIAFRONTINOGIRALDOGIRARDOTAGRANADAGUADALUPEGUARNEGUATAPÉGÓMEZ PLATAHELICONIAHISPANIAITAGÜÍITUANGOJARDÍNJERICÓLA CEJALA ESTRELLALA PINTADALA UNIÓNLIBORINAMACEOMARINILLAMEDELLÍNMONTEBELLOMURINDÓMUTATÁNARIÑONECHÍNECOCLÍOLAYAPEQUEPEÑOLPUEBLORRICOPUERTO BERRÍOPUERTO NAREPUERTO TRIUNFOREMEDIOSRETIRORIONEGROSABANALARGASABANETASALGARSAN ANDRÉS DE CUERQUIASAN CARLOSSAN FRANCISCOSAN JERÓNIMOSAN JOSÉ DE LA MONTAÑASAN JUAN DE URABÁSAN LUISSAN PEDROSAN PEDRO DE URABÁSAN RAFAELSAN ROQUESAN VICENTESANTA BÁRBARASANTA ROSA DE OSOSSANTAFÉ DE ANTIOQUIASANTO DOMINGOSEGOVIASONSÓNSOPETRÁNTARAZÁTARSOTITIRIBÍTOLEDOTURBOTÁMESISURAMITAURRAOVALDIVIAVALPARAÍSOVEGACHÍVENECIAVIGÍA DEL FUERTEYALÍYARUMALYOLOMBÓYONDÓZARAGOZA')]</value>
      <webElementGuid>1a62f05d-98b1-4815-9d6f-34248236c1fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
