<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Iniciar con_USERPASSWORDContainer_Us_b9789e_1</name>
   <tag></tag>
   <elementGuidId>239ff7ad-0c67-4a99-a32c-e3fd842dd87d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='USERPASSWORDContainer_Userpassword_spwd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#USERPASSWORDContainer_Userpassword_spwd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6763b0dc-93ea-4426-a711-453c3d7155fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>8405ac0e-3419-4b47-803d-1181c0fa3b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b32eea02-980d-4066-8571-e428ae7546e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USERPASSWORDContainer_Userpassword_spwd</value>
      <webElementGuid>519ec957-ac22-41bc-8cff-f1743fa0ccd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ocultar Contraseña</value>
      <webElementGuid>f8e8a32f-b17e-45ba-b9ce-25a17dec7477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USERPASSWORDContainer_Userpassword_spwd&quot;)</value>
      <webElementGuid>6903f494-92fa-4689-83eb-b2c514d07bc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='USERPASSWORDContainer_Userpassword_spwd']</value>
      <webElementGuid>8f0fcb30-43ed-4d2c-8546-880ad2403486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='USERPASSWORDContainer']/div/span/button</value>
      <webElementGuid>8cfcb824-e65d-4074-a9a8-75bb4236af89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar con'])[1]/following::button[1]</value>
      <webElementGuid>2e650c80-037a-42e9-a6a7-7ecc748d573b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar Sesión'])[1]/following::button[1]</value>
      <webElementGuid>ae66700a-477e-4d8a-b91c-52d49db091c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mantenerme conectado'])[1]/preceding::button[1]</value>
      <webElementGuid>b0891414-7793-4cc4-a9a3-f5dbe708f963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mantenerme conectado_'])[1]/preceding::button[1]</value>
      <webElementGuid>0565a7e2-2188-44b3-af9c-8a111e6fd4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>943d6595-db13-4c11-bb0f-6477ba3b04c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'USERPASSWORDContainer_Userpassword_spwd' and @title = 'Ocultar Contraseña']</value>
      <webElementGuid>67e832e9-f5ae-4a06-99e4-45a9375af77c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
