<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Iniciar con_USERPASSWORDContainer_Us_b9789e</name>
   <tag></tag>
   <elementGuidId>55c92625-21db-4d79-9388-bc83bbb4c2bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='USERPASSWORDContainer_Userpassword_spwd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#USERPASSWORDContainer_Userpassword_spwd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f2e68a58-163a-4575-919b-133bd2a00a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>691acd5f-6eba-4340-a162-9592eeb78d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82612e08-8d58-43ab-856d-2da6e3703ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USERPASSWORDContainer_Userpassword_spwd</value>
      <webElementGuid>516ff4ed-d1e5-493a-9b2e-d85a1242498d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mostrar Contraseña</value>
      <webElementGuid>f5a6ab7e-10d3-41c3-b2bf-38e32205fb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USERPASSWORDContainer_Userpassword_spwd&quot;)</value>
      <webElementGuid>2511a868-7f36-4760-a9ec-ea497b3e36a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='USERPASSWORDContainer_Userpassword_spwd']</value>
      <webElementGuid>76c19199-682e-43be-84fc-705b6a101613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='USERPASSWORDContainer']/div/span/button</value>
      <webElementGuid>9a487625-d52c-43e1-8a86-a7c87a5a5a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar con'])[1]/following::button[1]</value>
      <webElementGuid>93885cc1-0b82-4183-9c59-5f60b865093b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar Sesión'])[1]/following::button[1]</value>
      <webElementGuid>773cb575-21ce-495a-8f7b-849759217c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mantenerme conectado'])[1]/preceding::button[1]</value>
      <webElementGuid>a96f7d3f-58d9-4cdd-a4a6-61a27551f4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mantenerme conectado_'])[1]/preceding::button[1]</value>
      <webElementGuid>542d64b2-541b-4547-bfa4-71e05997a734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f4493da2-478b-45fa-b4b2-3a7bfd655580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'USERPASSWORDContainer_Userpassword_spwd' and @title = 'Mostrar Contraseña']</value>
      <webElementGuid>f0cc9746-9889-422f-bb6d-fbbc21fd968d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
