<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Iniciar con_USERPASSWORDContainer_Use_26b53f</name>
   <tag></tag>
   <elementGuidId>3b23ffab-0d2c-40cb-8c92-96e500d4849e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USERPASSWORDContainer_Userpassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#USERPASSWORDContainer_Userpassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b848e009-1ae7-4d84-88b2-e9e8d7860824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0e60db2c-4191-4131-a03f-bbbf633d4923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USERPASSWORDContainer_Userpassword</value>
      <webElementGuid>6375e522-0c3c-4023-b7d9-bb7ae7d53262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USERPASSWORDContainer_Userpassword</value>
      <webElementGuid>afe647b3-ad02-44c2-b77b-b7ad3b9e00bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control Attribute_Trn AttributeLogin</value>
      <webElementGuid>ed319438-638d-472e-9b26-6fd6157a05ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>fbe56ab7-bea3-4f3e-850e-b652384043fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c3b5d8d4-65cd-4498-b7e3-9c59821e3373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this,95,'',false,'',0)</value>
      <webElementGuid>d7037704-7ba2-49f8-8b97-89b70c964cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.evt.onchange(this)</value>
      <webElementGuid>dbc0193e-4a98-478e-af99-74012190c096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>gx.evt.onblur(this,95);</value>
      <webElementGuid>b3f7d5eb-fd3a-4747-b284-6ef5aa8fa330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b310a8b4-4dd8-49ba-b64f-6c518e053f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USERPASSWORDContainer_Userpassword&quot;)</value>
      <webElementGuid>fcc4463e-6b7c-47b0-9ecd-f11b47d67258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USERPASSWORDContainer_Userpassword']</value>
      <webElementGuid>a343de91-b645-4cd6-8810-0c854aaacada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='USERPASSWORDContainer']/div/input</value>
      <webElementGuid>c49b4b30-6366-446e-8a4f-8b5acf580461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>7c0d3076-2f26-4f8e-b8b7-0af5b5d9bce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'USERPASSWORDContainer_Userpassword' and @name = 'USERPASSWORDContainer_Userpassword' and @placeholder = 'Contraseña']</value>
      <webElementGuid>a8237f86-8342-4457-bf71-161752c12de1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
