<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Por favor ingrese en siguiente texto_LOGIN</name>
   <tag></tag>
   <elementGuidId>49239ab8-28dd-4270-a983-c78944c62bf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LOGIN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LOGIN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de65d945-fdb9-46a2-b739-c289d7f927d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6d73a2a-8c80-4fe1-ac43-d90d49695df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>f6976dbe-a918-4228-ab1a-32e658f67fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>92aa9b22-ac8f-4170-9d92-0afb0beb6fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Entrar</value>
      <webElementGuid>c44f5954-5012-4147-a40d-396cf49964be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>K2BToolsButton_MainAction btn btn-default</value>
      <webElementGuid>3104c205-56ad-4104-b246-21e7502b4f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>327e03af-f6f0-49b0-8722-f770d99fc5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 139,'',false,'',0)</value>
      <webElementGuid>1abd1c96-1f11-4499-97da-b888b2a95041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt-control</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>63b326d5-cc30-403c-af1b-d31b879c8f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;&quot;,false]</value>
      <webElementGuid>a8895433-5d00-43a7-ba70-9a31274079ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LOGIN&quot;)</value>
      <webElementGuid>f3b2e19a-7d3b-429a-a71c-f70dfb95a1ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LOGIN']</value>
      <webElementGuid>a63bf566-d008-4d9f-9ba2-0b957d80f235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TABLE22']/div[2]/div/input</value>
      <webElementGuid>9585d94f-cb48-4315-813b-54106a8cb1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5f832a8a-bef4-4e99-af64-7596ff68293f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'LOGIN' and @id = 'LOGIN']</value>
      <webElementGuid>58054c2b-dd87-4e05-bbe0-283bf81db891</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
