<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Iniciar con_USERPASSWORDContainer_Use_26b53f</name>
   <tag></tag>
   <elementGuidId>5700176b-42af-4b39-9048-7f75d37cc61b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USERPASSWORDContainer_Userpassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#USERPASSWORDContainer_Userpassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ca7852c-3c6a-44b2-858f-55a25e5c2fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>881ae317-a5a5-47d7-a4f1-b54ec01873e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USERPASSWORDContainer_Userpassword</value>
      <webElementGuid>79948ac7-9d12-4655-b181-17f8ea539f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USERPASSWORDContainer_Userpassword</value>
      <webElementGuid>500a1c0c-c346-468e-92c6-0a2b88fabdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control Attribute_Trn AttributeLogin</value>
      <webElementGuid>4b1ae0a7-d2c3-4f88-a2e4-eddfe3c2b370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>6c323076-9abe-438b-8f23-e19a0af4c90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f3d7f981-4d4a-4773-9d5e-9d5af01962a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this,95,'',false,'',0)</value>
      <webElementGuid>82b9cfcf-5ef1-4d06-87b1-fafd5c2317e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.evt.onchange(this)</value>
      <webElementGuid>2266425f-e107-4737-87e4-bb30e2e299ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>gx.evt.onblur(this,95);</value>
      <webElementGuid>3fb2cf60-0eb1-4110-89b7-ab27faf1da66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>12faff10-f50b-44bd-bd66-3419f33fa25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USERPASSWORDContainer_Userpassword&quot;)</value>
      <webElementGuid>dd20d991-243d-4d65-ba50-20f2e25e21cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USERPASSWORDContainer_Userpassword']</value>
      <webElementGuid>f5fdb9db-6e66-4f3b-a307-7b0e47400725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='USERPASSWORDContainer']/div/input</value>
      <webElementGuid>4bb8beea-3289-410d-9bb7-c684f9926176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>d1b824a2-33f1-406c-840e-31e2b34d42eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'USERPASSWORDContainer_Userpassword' and @name = 'USERPASSWORDContainer_Userpassword' and @placeholder = 'Contraseña']</value>
      <webElementGuid>75ccec70-643d-4a1c-b8b1-5df4e7cf7445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
