<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Iniciar con_USERPASSWORDContainer_Use_26b53f</name>
   <tag></tag>
   <elementGuidId>1ff62798-fbe1-4ab0-a9ca-5935cc6bd042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#USERPASSWORDContainer_Userpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USERPASSWORDContainer_Userpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d4d5070-7e12-4caf-bc79-83f0084e6107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bbce5769-3dc1-4d4d-9398-0fc58ea18b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USERPASSWORDContainer_Userpassword</value>
      <webElementGuid>bd79a380-b8fc-4643-8e42-3e1875218ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USERPASSWORDContainer_Userpassword</value>
      <webElementGuid>ad290753-cc10-4196-87ca-450bd9062548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control Attribute_Trn AttributeLogin</value>
      <webElementGuid>c852f6c7-e268-45d7-84cb-b7c10b66952d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>be4d7d01-3c22-496d-a48b-1e7fef2ee37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7f92491c-4b59-4594-a7bd-d5721177c759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this,95,'',false,'',0)</value>
      <webElementGuid>d9680428-98d1-41fa-9fd1-cc13ab18f9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.evt.onchange(this)</value>
      <webElementGuid>5ecb34b6-440f-4bb7-bc8a-0b2dc21c9c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>gx.evt.onblur(this,95);</value>
      <webElementGuid>d4322954-d33b-43b2-9503-c3cfa87d539f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>daf86adf-4a8c-4d10-bbc4-2ac63a65bc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USERPASSWORDContainer_Userpassword&quot;)</value>
      <webElementGuid>90912a8f-16cf-46f0-a188-35cbd70e716e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USERPASSWORDContainer_Userpassword']</value>
      <webElementGuid>73da40c8-500f-489d-9216-dbdf19889e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='USERPASSWORDContainer']/div/input</value>
      <webElementGuid>2a0e7249-c1e8-4f80-bc21-4c66161b6953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>3922be3d-1efc-4bc2-82cd-99664beb32ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'USERPASSWORDContainer_Userpassword' and @name = 'USERPASSWORDContainer_Userpassword' and @placeholder = 'Contraseña']</value>
      <webElementGuid>30ec1795-9498-437a-9661-a24c32fbbf97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
