<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sociopoltica</name>
   <tag></tag>
   <elementGuidId>f70cb4f0-7715-4269-9da2-bfe57609b043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.mm-collapse.mm-show > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='K2baccordionmenu']/li/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5229a9ec-8981-4a65-a904-12e07e378ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sociopolítica</value>
      <webElementGuid>dcf2cf62-e139-45a5-88e5-8680126f09b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;K2baccordionmenu&quot;)/li[@class=&quot;mm-active&quot;]/ul[@class=&quot;mm-collapse mm-show&quot;]/li[1]/a[1]</value>
      <webElementGuid>9b1541bc-1391-4836-8109-88f0b650ccca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='K2baccordionmenu']/li/ul/li/a</value>
      <webElementGuid>2acd4195-2b01-44be-96ff-fb7f0de4607e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administración'])[1]/following::a[1]</value>
      <webElementGuid>86b3d5aa-d81d-4467-8ae4-5cc927420045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCITECH 1'])[1]/following::a[5]</value>
      <webElementGuid>97225b43-0a65-4213-b59a-bf7ae049102b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Países'])[1]/preceding::a[1]</value>
      <webElementGuid>0b5c56de-11a3-431e-a147-71a98f1ff75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>575dd4cf-4c39-4736-8ef3-600fd37a7b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Sociopolítica' or . = 'Sociopolítica')]</value>
      <webElementGuid>9ddd71c2-7721-409d-b7f7-55367d9b8493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
