<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Bienvenido(a)</name>
   <tag></tag>
   <elementGuidId>77216731-99a0-48c4-940d-63ecfb7b7636</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='W0009LBLWELCOME']/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>8d9c4a46-55f4-4b3a-ad10-d76beac90341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bienvenido(a)</value>
      <webElementGuid>86bc486f-1a39-4c4e-9a6e-3d6ba758ca3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0009LBLWELCOME&quot;)/b[1]</value>
      <webElementGuid>6062ea13-9ca2-4742-a880-a4523011c967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0009LBLWELCOME']/b</value>
      <webElementGuid>54068b23-1c7c-4a57-b999-a63d76ad485c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asignar Permisos a Rol'])[1]/following::b[1]</value>
      <webElementGuid>275ad219-e802-4d03-a16d-e0c7d0c6a4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PQRS'])[1]/preceding::b[1]</value>
      <webElementGuid>b3105465-918b-405b-86ab-2dd6d4d07da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat en linea'])[1]/preceding::b[1]</value>
      <webElementGuid>fedcdf9b-0539-4216-9f30-4b8f570dcdc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bienvenido(a)']/parent::*</value>
      <webElementGuid>86130de2-83bd-4975-89dc-4b96da927d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>f8556a0f-b1d3-47c9-bc8a-a3002133ca04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Bienvenido(a)' or . = 'Bienvenido(a)')]</value>
      <webElementGuid>89c13a1a-433e-45c1-89a9-cad597b4a2c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
