<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Estado_INSERT</name>
   <tag></tag>
   <elementGuidId>6ec804d9-9912-45d0-ada8-87b55e27ad26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='INSERT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#INSERT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>585e00d9-2670-4034-9261-68fc39a07e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95bbcd68-c200-4ffa-89c3-af847d7dbcc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>INSERT</value>
      <webElementGuid>dd085ee7-89c1-46b7-bb0b-d30342dd7ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>INSERT</value>
      <webElementGuid>bb56e121-11f4-4ec9-8a5e-0ad17c5196c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Nuevo</value>
      <webElementGuid>e1377616-c0be-4263-86a2-90c2ea031da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Agregar</value>
      <webElementGuid>e1af1bcd-71a5-40d3-ba45-3e9ae9d0ffcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>K2BToolsButton_MainAction btn btn-default</value>
      <webElementGuid>30f6efe3-0bfb-4920-8571-86f96640a7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>396f787f-f6bb-4106-916e-32505fbebc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 56,'',false,'',0)</value>
      <webElementGuid>f9a1cd66-6a54-4b7c-8d1c-2d4218aa6487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-evt-control</name>
      <type>Main</type>
      <value>INSERT</value>
      <webElementGuid>2da8d431-810a-488b-94a8-050c3791624d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;&quot;,false]</value>
      <webElementGuid>571bb03a-6976-438b-bee5-6b1a182a265d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;INSERT&quot;)</value>
      <webElementGuid>37eeb93d-02f8-4166-ab64-91cac953dea7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='INSERT']</value>
      <webElementGuid>8eda83b7-72a3-4699-83d5-b8f89be59cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='K2BTABLEGRIDACTIONSLEFTCONTAINER']/tbody/tr/td/input</value>
      <webElementGuid>7d9ae1b4-711f-4646-a4eb-92a2362df6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>8083550d-bca0-4115-ba9e-984b8c088811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'INSERT' and @id = 'INSERT' and @title = 'Agregar']</value>
      <webElementGuid>acc66517-4380-4f5f-ac3d-5e7f810fcef1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
