<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Segundo nombre_W0026W0007W0012PATNOMSEG</name>
   <tag></tag>
   <elementGuidId>a740fb01-e8bb-4f41-abaf-75ebe7b7a14f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0026W0007W0012PATNOMSEG']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012PATNOMSEG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afe9ad03-d9ca-48b5-8e70-1b26a59310be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb7fedc9-debb-46cf-8c2e-a8e65611ec45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012PATNOMSEG</value>
      <webElementGuid>c9be2eda-1fc2-4178-8d6f-26b03b2c9a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012PATNOMSEG</value>
      <webElementGuid>c2e0fe4d-8e6a-4740-9974-aa694806f996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>39b04259-5e64-4406-980f-e30efcd21e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9fa6265e-a6d2-4063-a800-8321165d0bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f8692574-d2fd-4993-b8fe-3ef12f1b68fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn form-control</value>
      <webElementGuid>294910f7-2e34-47db-915d-581b26307f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 36,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>b75b54b2-79c8-4ac5-a2f5-8378fae13670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.value=this.value.toUpperCase();;gx.evt.onchange(this, event)</value>
      <webElementGuid>4d9e0fcf-6514-4617-ad6f-033bde2e28c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>this.value=this.value.toUpperCase();;gx.evt.onblur(this,36);</value>
      <webElementGuid>2ea232e6-261c-43fb-9ec6-c63d876a6a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0026W0007W0012&quot;,false]</value>
      <webElementGuid>b78c035d-8cd1-4d55-8ce7-34c8e50cb6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012PATNOMSEG&quot;)</value>
      <webElementGuid>7ccb7531-ea56-4f88-a627-2f549dff2058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0026W0007W0012PATNOMSEG']</value>
      <webElementGuid>a22af0f2-daf9-4a08-9186-762d12ca226a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012TABLEATTRIBUTESINFORMSECTION1']/div[4]/div[2]/div/div/input</value>
      <webElementGuid>fe133003-abac-42af-a237-617af7c5b64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>41abf948-4b5b-4042-b806-5dfcb491e839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'W0026W0007W0012PATNOMSEG' and @name = 'W0026W0007W0012PATNOMSEG']</value>
      <webElementGuid>a54ce261-e29b-4ec2-aba8-b9263079401b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
