<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero Identificacin_W0026W0007W0012PATNUMIDE</name>
   <tag></tag>
   <elementGuidId>e2eaa3ba-0936-4e8e-bd7f-a8bdd8a7802f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='W0026W0007W0012PATNUMIDE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012PATNUMIDE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f4695ac-2a3e-4515-ac99-20c634fa3b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3067e7eb-b693-4cff-ba1c-431e3d184ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012PATNUMIDE</value>
      <webElementGuid>eb265e71-72ea-4cc9-ad68-4b1914c1f840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012PATNUMIDE</value>
      <webElementGuid>95ff2c74-97fa-4f70-9775-fba82080efe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>d8c9ca95-3dd7-4be7-8b4c-bd77f5243127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7b626d06-5b0c-408e-8156-6fba394f405e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4c394562-5fba-481d-a96b-22e3e5ef77cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn Attribute_Required form-control</value>
      <webElementGuid>fca3098a-fad9-4aa4-9328-5f594df7ee1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 27,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>3cc385b7-3348-4a6b-b88d-8ec449a489f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.value=this.value.toUpperCase();;gx.evt.onchange(this, event)</value>
      <webElementGuid>a11c5845-b729-4f93-aa70-5321db827a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>this.value=this.value.toUpperCase();;gx.evt.onblur(this,27);</value>
      <webElementGuid>bcd3c159-61db-418e-8c36-8907787d9e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;W0026W0007W0012&quot;,false]</value>
      <webElementGuid>54c08eee-6b9b-4e7e-8944-fe0537fbfed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f5098bc2-c174-493c-94a4-20c1c601f7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012PATNUMIDE&quot;)</value>
      <webElementGuid>cd164c23-9727-4796-9080-309d9af175e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='W0026W0007W0012PATNUMIDE']</value>
      <webElementGuid>fbde2b47-abdc-48a6-b7ef-f2b071df6214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012TABLEATTRIBUTESINFORMSECTION1']/div[3]/div/div/div/input</value>
      <webElementGuid>97682c24-c02b-4815-a725-430d569e6a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>d1f5c4df-6828-4002-bdef-ac5578283fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'W0026W0007W0012PATNUMIDE' and @name = 'W0026W0007W0012PATNUMIDE']</value>
      <webElementGuid>f9e34478-0d28-4a7d-9d1d-589e392f8148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
