<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione.CDULA DE CIUDADANACDULA D_f8deef</name>
   <tag></tag>
   <elementGuidId>6f87ff9d-a4e2-4e4c-8b37-8c973f116c8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='W0026W0007W0012PATTIPIDESEC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#W0026W0007W0012PATTIPIDESEC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dc4639d8-54e8-4962-a7f6-cf8d98aa493e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>W0026W0007W0012PATTIPIDESEC</value>
      <webElementGuid>524cef01-12a9-447c-a77d-55a5e316e59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>W0026W0007W0012PATTIPIDESEC</value>
      <webElementGuid>b02210ae-3f51-4c20-93d2-b75bcb135130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute_Trn Attribute_Required form-control</value>
      <webElementGuid>0d7cbb3d-d6d9-4b4b-a9fd-d385c4f123fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
      <webElementGuid>6f103e6c-bd30-4831-a124-e4300dee5e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 22,'W0026W0007W0012',false,'',0)</value>
      <webElementGuid>ea1e1638-3499-485e-96f8-ba38effb1ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;gx.evt.onchange(this, event)</value>
      <webElementGuid>f8844cb7-d49b-4917-b81c-ed054dfe31eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,22);</value>
      <webElementGuid>b8434870-c5fd-46e7-9214-f5e56a3f9e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1d29398c-2432-4b04-93ae-3e1ec77cb327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Seleccione...CÉDULA DE CIUDADANÍACÉDULA DE EXTRANJERIANITNO APLICAPASAPORTEPERMISO ESPECIAL DE PERMANENCIAPERMISO POR PROTECCION TEMPORALTARJETA DE IDENTIDAD</value>
      <webElementGuid>40135268-2bfa-4013-8e7c-7e6a81b928f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;W0026W0007W0012PATTIPIDESEC&quot;)</value>
      <webElementGuid>8b71efe2-3b33-4de7-a71c-03ea5851fedf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='W0026W0007W0012PATTIPIDESEC']</value>
      <webElementGuid>a3c38a3c-c782-497d-ac59-5bd0b60f705b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='W0026W0007W0012TABLEATTRIBUTESINFORMSECTION1']/div[2]/div/div/div/select</value>
      <webElementGuid>4ec9c1d2-0eca-40e6-a735-f3bdd77f3a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Identificación'])[1]/following::select[1]</value>
      <webElementGuid>4e5320fd-ce0a-47fa-9647-cbd744bc098f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participante'])[1]/following::select[1]</value>
      <webElementGuid>07168c2b-56fb-4bb1-8248-f535810e65d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número Identificación'])[1]/preceding::select[1]</value>
      <webElementGuid>9208d9bd-0a01-4d51-ae7b-a3660e7ae7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primer nombre'])[1]/preceding::select[1]</value>
      <webElementGuid>5ffe72e0-7c87-48e0-8a19-ea70545779de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9fdd7d9f-a244-48df-9d75-ceb10fdf34fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'W0026W0007W0012PATTIPIDESEC' and @name = 'W0026W0007W0012PATTIPIDESEC' and (text() = '
Seleccione...CÉDULA DE CIUDADANÍACÉDULA DE EXTRANJERIANITNO APLICAPASAPORTEPERMISO ESPECIAL DE PERMANENCIAPERMISO POR PROTECCION TEMPORALTARJETA DE IDENTIDAD' or . = '
Seleccione...CÉDULA DE CIUDADANÍACÉDULA DE EXTRANJERIANITNO APLICAPASAPORTEPERMISO ESPECIAL DE PERMANENCIAPERMISO POR PROTECCION TEMPORALTARJETA DE IDENTIDAD')]</value>
      <webElementGuid>304c51e3-ee6c-4aa8-855e-e88d531fe75f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
