<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Iniciar con_USERPASSWORDContainer_Use_26b53f</name>
   <tag></tag>
   <elementGuidId>73728d38-c7ef-406c-b0fc-0eb0192bee1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USERPASSWORDContainer_Userpassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#USERPASSWORDContainer_Userpassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0b9bd95-3734-4ba9-9a75-a01fc6f0f637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>98be0523-543a-4c06-9f34-b9c40be8aa3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USERPASSWORDContainer_Userpassword</value>
      <webElementGuid>ba3cb591-1990-41a0-8587-73d03177631e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USERPASSWORDContainer_Userpassword</value>
      <webElementGuid>a1dd187d-5e0b-4af0-aa5f-dc224847d24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control Attribute_Trn AttributeLogin</value>
      <webElementGuid>44a4da0e-0262-49c1-ae05-dca83d95a80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>84dd5f8e-7700-43c0-bd77-81aff76fda2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>44354426-d493-4cde-a5b7-fa264b7b936a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this,95,'',false,'',0)</value>
      <webElementGuid>232c683d-b1de-4885-88f6-f4bf3a69f8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.evt.onchange(this)</value>
      <webElementGuid>f015e19a-9c21-4125-8d9b-0e5b345aaab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>gx.evt.onblur(this,95);</value>
      <webElementGuid>f1c4068b-7c64-48c8-bb22-9cc101ac147b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a8d94be5-12f0-4d0a-9c09-ebf0b8830299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USERPASSWORDContainer_Userpassword&quot;)</value>
      <webElementGuid>c57fcdcc-ab16-4e29-a931-806e204c7a20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USERPASSWORDContainer_Userpassword']</value>
      <webElementGuid>1c40a7c9-d94a-45bc-88e0-3baa1bb2c825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='USERPASSWORDContainer']/div/input</value>
      <webElementGuid>08da3bc4-0636-4235-bb34-6ca1585ce324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>04f5844c-9367-45a6-ba7c-045c1d9c6323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'USERPASSWORDContainer_Userpassword' and @name = 'USERPASSWORDContainer_Userpassword' and @placeholder = 'Contraseña']</value>
      <webElementGuid>a2ce8b22-9bb7-4e13-880e-659309dc2b80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
